### ISSUE TITLE
rename back to just "istanbul"?

### ISSUE THREAD

**Issue by graingert** [istanbuljs/istanbuljs#1]

**Comment by JaKXz** [comment]
I think the `js` suffix makes google searching much easier. searching for `istanbuljs` turns up closer results to code coverage than the city `istanbul`.

this suffix is especially helpful when searching for `nyc` and I think is a general pattern in the community.

**Comment by graingert** [comment]
There's not too much of a problem removing "js" from library names. To get to something about 'angular' (not the JS framework) I had to search Google for 'angular -js -io -framework -php -app -AngularJS -TypeScript -module -code'

**Comment by JaKXz** [comment]
Yes, I think that's because angular is much more prevalent as a framework than "thinking about angles"

try: https://www.google.ca/?gws_rd=ssl#newwindow=1&q=istanbul+-js+-nyc

**Comment by graingert** [comment]
searching for `instanbul js` gets you to https://github.com/gotwarlost/istanbul

**Comment by graingert** [comment]
it would be good to get @gotwarlost/istanbul then reparent 8c4a22fd45f68fe34769c54c7d97f532e089eaa2 onto it.

**Comment by JaKXz** [comment]
https://istanbul.js.org is the 3rd or 4th result in the search for `istanbul js`.

I think the point of the work we're doing now is to move that result up to the top, as well as eventually mark the older istanbul libraries as deprecated and redirecting people to https://istanbul.js.org [when we've also beefed up the documentation].

**Comment by JaKXz** [comment]
> it would be good to get @gotwarlost to move gotwarlost/istanbul to istanbuljs/istanbul then reparent 8c4a22f onto it.

I agree that re-parenting the commit is a good idea, but my final thought on this 🚲 🏚 is that the `js` suffix is valuable and should remain.

**Comment by graingert** [comment]
> I think the point of the work we're doing now is to move that result up to the top

Off topic, but I'd like to move off of .js.org

**Comment by bcoe** [comment]
Sorry I'm late to this thread, I'd like to keep the `js` suffix too; mainly because I don't want their to be confusion with the first version of `istanbul` which is still a wildly popular GitHub repo:

https://github.com/gotwarlost/istanbul
