### ISSUE TITLE
Hook code run with `eval`

### ISSUE THREAD

**Issue by jsoo1** [istanbuljs/istanbuljs#103]
It would be very helpful to get coverage when `eval`ing code from a test file:
```js
var testCode = fs.readFileSync('src-file.js', 'utf-8')
...
eval(testCode)
```

**Comment by bcoe** [comment]
@jsoo1 this has been requested by a few folks; I'm not quite sure what it would end up looking like, as test coverage is tied to a file currently. open to suggestions however 👍

**Comment by coreyfarrell** [comment]
I believe this is impossible to directly support.  I don't think we can directly hook `eval()` as it is a [JavaScript global object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval), plus as @bcoe pointed out nyc needs to associate coverage with a filename.  To accomplish your goal you would have to use istanbul-lib-instrument (or babel.transform + babel-plugin-istanbul) to pre-instrument the code then run that instrumented code in the eval.

Another option (probably better if you are targetting node.js) would be to use [vm.runInThisContext](https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options) instead.  nyc can hook this method, just be sure to pass the filename in the options object.

**Comment by jsoo1** [comment]
Makes sense. I don’t use this anymore. Is there any reason not to close?

**Comment by coreyfarrell** [comment]
> Is there any reason not to close?

Sorry I don't understand, I did close this ticket.

**Comment by jsoo1** [comment]
Oh oops. Thank you!
