### ISSUE TITLE
Documentation for babel missing info on babel-preset-es2015

### ISSUE THREAD

**Issue by basickarl** [istanbuljs/istanbuljs#105]
https://istanbul.js.org/docs/tutorials/es2015/#prerequisites

The bullet list is missing the reason why `babel-preset-es2015` is to be installed.

Another note, ddocumentation in general is not very friendly.

**Comment by JaKXz** [comment]
Feel free to make a PR to help clarify this, if you still feel that way - the paragraph before the install command does explain the use of `babel-preset-es2015`.

That being said, this is a good reminder for me to update to using `babel-preset-env`. 👍 I am going to close this for now, though. Specific feedback on what is not helpful would be great, thanks!
