### ISSUE TITLE
TypeError: Invalid Version: https://registry.npmjs.org/istanbul-lib-instrument/-/istanbul-lib-instrument-1.8.0.tgz

### ISSUE THREAD

**Issue by chrisdevereux** [istanbuljs/istanbuljs#109]
istanbul-lib-instrument (installed as a dependency of nyc) is throwing for me due to an incorrect value being passed to semver.

I have tracked the issue down to this line in [constants.js](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/constants.js):

```
// name of coverage data magic value
export const MAGIC_VALUE = createHash(SHA).update(name + '@' + major(version)).digest('hex');
```

`version` is taken from the version field of package.json, apparently assuming that version will be the same as the one defined in the repository's package.json. However, for some reason npm has assigned the field the tarball address on install, causing the exception `TypeError: Invalid Version: https://registry.npmjs.org/istanbul-lib-instrument/-/istanbul-lib-instrument-1.8.0.tgz` to be thrown.

It seems that npm only does this under some circumstances, so it may be difficult to reproduce. Unsure whether this is really an issue with istanbul or npm.

**Comment by bcoe** [comment]
@chrisdevereux try removing `package-lock.json` and installing, I think I saw something along these lines recently and fixed it using this approach.

**Comment by ninahaack** [comment]
I'm having the same problem when I try to do `npm run test -- --coverage`

**Comment by bcoe** [comment]
@ninahaack please try:

```
rm package-lock.json`
rm -rf node_modules/*
npm i
```

**Comment by ninahaack** [comment]
It worked @bcoe, thanks! But it means that I can't have the package-lock in project?

**Comment by bcoe** [comment]
@ninahaack you should be able to use a package-lock.json going forward; I recommend opening an issue on `npm/npm` which references this -- feels like a bug with package-lock that the CLI team would love to fix.

**Comment by ninahaack** [comment]
I will do it, thanks again @bcoe

**Comment by JaKXz** [comment]
Closing this issue in favour of the one on npm/npm ☝️
