### ISSUE TITLE
`getPreamble` and visitor/coverageTemplate... modifying the block at the top of a file

### ISSUE THREAD

**Issue by gregglind** [istanbuljs/istanbuljs#116]
We have an odd use case:  instrumenting Firefox Legacy Addons.  The old 'getPreamble' function was enough to get us much of the way there.  That equivalent function is in Visitor, but not modifiable.  Thoughts welcome on making that more exposed.

Thanks!

**Comment by bcoe** [comment]
Hey @gregglind, I'm definitely open to exposing this functionality in the Visitor. Would you like to take a crack at the work? Since you know your specific requirements, I would appreciate the help.

**Comment by coreyfarrell** [comment]
I'm unsure what is wanted here.  Are you still pursuing this?  What do you want to modify in the coverage template?

**Comment by coreyfarrell** [comment]
Let us know if this is still being pursued and exactly what is needed.  Closing for now.
