### ISSUE TITLE
istanbul-lib-instrument: compatibility with babel@7

### ISSUE THREAD

**Issue by scholtzm** [istanbuljs/istanbuljs#119]
Since `@babel/core@7.0.0-beta.33`, this package started logging this statement in the [console](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/visitor.js#L223):

`Unable to process function body node type: ArrowFunctionExpression`

According to [release notes](https://github.com/babel/babel/releases/tag/v7.0.0-beta.33), there have been some breaking changes, namely:

> removing expression field from ArrowFunctionExpression.

Used packages:

```
"@babel/core": "^7.0.0-beta.34"
"babel-plugin-istanbul": "^4.1.5" (which uses istanbul-lib-instrument)
```

Also let me know if I should move this issue over to [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul).

**Comment by tswaters** [comment]
Looks like the instrumenter is attempting to turn a single-statement arrow function into a body expression so it can include coverage information.  

With `expression` no longer being set, this is the line where it fails : https://github.com/istanbuljs/istanbuljs/blob/istanbul-lib-instrument%401.9.1/packages/istanbul-lib-instrument/src/visitor.js#L346

In addition to that `n.expression` check (which always fails), it can also check if  `n.body.type  !== 'BlockStatement'`.  

I've gleaned that from the PR that removed the expression flag - https://github.com/babel/babel/commit/6d820a27578254603ad6d6623277f31d5410a37c#diff-ee87f4557718082c04846c8310df0788R254

**Comment by tilgovi** [comment]
For anyone else eager for this, here's a slow (extra traversal) hack I added to my plugins for the moment:

```js
// Restore old babylon behavior for istanbul.
// https://github.com/babel/babel/pull/6836
// https://github.com/istanbuljs/istanbuljs/issues/119
function hacks() {
  return {
    visitor: {
      Program(programPath) {
        programPath.traverse({
          ArrowFunctionExpression(path) {
            const node = path.node;
            node.expression = node.body.type !== 'BlockStatement';
          },
        });
      },
    },
  };
};
```

**Comment by domharrington** [comment]
Thanks @tilgovi. To clarify for future readers, this can be added as a babel plugin and added to your plugins array:

```json
"plugins": ["./arrow-function-coverage-fix.js"],
```

```js
// Restore old babylon behavior for istanbul.
// https://github.com/babel/babel/pull/6836
// https://github.com/istanbuljs/istanbuljs/issues/119
module.exports = function hacks() {
  return {
    visitor: {
      Program(programPath) {
        programPath.traverse({
          ArrowFunctionExpression(path) {
            const node = path.node;
            node.expression = node.body.type !== 'BlockStatement';
          },
        });
      },
    },
  };
};
```

This does add a performance hit, but it's better than having to drop coverage requirements.

**Comment by jmbothe** [comment]
Is there a chance that this bug could somehow impact the veracity of coverage output? I am getting these warnings about `ArrowFunctionExpression`, but another collaborator on the same project is not getting them (for what reason, I don't know). [His output is showing 100% coverage across the board](https://user-images.githubusercontent.com/1757435/35486361-f809bbba-043a-11e8-9963-1db43e50edd2.png), while mine shows this:

![nyc error output](https://user-images.githubusercontent.com/28688602/35488773-b8f62ae6-045b-11e8-8bee-ac554644b0b7.GIF)

**Comment by jy95** [comment]
@jmbothe same for me : I cannot find out why ^^

![image](https://user-images.githubusercontent.com/9306961/35661186-d08a5896-0710-11e8-8ce7-606ba2453864.png)

If I apply the fix provided by @tilgovi , The function coverage drop out : 
![image](https://user-images.githubusercontent.com/9306961/35661266-4ab94d0c-0711-11e8-8f42-86741a302d3f.png)

**Comment by jy95** [comment]
@jmbothe I had the same problem but , in my case, I find the solution : arrow-function-coverage-fix.js should be before the babel-plugin-istanbul plugin like this : 

```js
plugins = ["./fix-coverage/arrow-function-coverage-fix.js", "babel-plugin-istanbul"]
````

My config : https://github.com/jy95/torrent-files-library/blob/master/.babelrc.js#L10

**Comment by AKFourSeven** [comment]
I am having the same issue however using 

```
"plugins": ["./arrow-function-coverage-fix.js"],
```

caused a major error 

```
Error: Reentrant plugin detected trying to load "path/to/app/arrow-function-coverage-fix.js". This module is not ignored and is trying to load itself while compiling itself, leading to a dependency cycle. We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore.
```

I am probably missing something here, I just don't know what it is...

**Comment by tilgovi** [comment]
@AKFourSeven, if you have the fix in a separate file, like you have, then you need to exclude that file from Babel. A module cannot be required by your Babel configuration and compiled by your Babel configuration at the same time.

Follow the error message instructions and add an ignore setting to your .babelrc or ignore file.
