### ISSUE TITLE
Is it possible to control the level of the instrumentation?

### ISSUE THREAD

**Issue by nadavye** [istanbuljs/istanbuljs#126]
Hi,
I'm using 'istanbul-lib-instrument' to create an instrumentor for static instrumentation and it causes the original JS to become huge - from 14MB to ~160MB.

Since I don't care about statement coverage, I wonder if there's a way to configure the instrumentor to generate code for methods and branches but not to generate statements related code?

I think that it may reduce the size drastically.

I'll appreciate your help.

Cheers,
Nadav

**Comment by nadavye** [comment]
BTW - If not, I don't mind contributing this feature, but I'll need some high level guidance.

**Comment by nadavye** [comment]
Ping

**Comment by coreyfarrell** [comment]
Sorry for the slow response.  This is related to #273 - we're considering dropping statements from the reports.

**Comment by RoniSegal** [comment]
Hi, any update on this one?

**Comment by coreyfarrell** [comment]
I looked at the code again and instrumentation requires statement coverage.  I do not see a way to reduce the amount of coverage collected as babel does not operate on lines.  Further collecting detailed coverage is explicit the goal of istanbuljs.  I'd be open to patches which reduce size without sacrificing functionality but reducing functionality is not something I'm really interested in.  I believe having an option to control this would introduce too much complexity.

I recommend looking at c8 and/or other native v8 based coverage collection techniques if you find the size of instrumented code problematic.
