### ISSUE TITLE
Branch coverage not 100% when using Jest to test Angular

### ISSUE THREAD

**Issue by ahnpnl** [istanbuljs/istanbuljs#134]
Hi,

I'm using Jest to test my Angular application. However, my branch coverage never gets to 100% because of the constructor. Can anyone help me with this ?

![image](https://user-images.githubusercontent.com/27772165/34822371-ffa61b1a-f6c6-11e7-9a37-85bdae445559.png)

This is my test code

![image](https://user-images.githubusercontent.com/27772165/34822395-15ca6234-f6c7-11e7-855c-49ab4b55ba88.png)

**Comment by blackholegalaxy** [comment]
same here on angular 5.0

**Comment by marshallmick007** [comment]
This issue still persists in Angular 7, and reports inaccurate coverage numbers for @Inputs() and @ViewChild() decorators as well as the constructors as mentioned in this issue. See #72 which unfortunately was closed.

**Comment by ahnpnl** [comment]
if you try `jest-preset-angular` at v7.0.0-alpha.2, the constructor coverage issue is fixed. I haven't tested with @Input or @ViewChild yet.

**Comment by bcoe** [comment]
@ahnpnl that's great to know that the constructor coverage issue is fixed; does `v7.0.0-alpha.2` use Babel 7?

**Comment by ahnpnl** [comment]
You can use Babel 7 as well but by default, jest preset angular uses tsc instead of Babel. To use Babel 7, you need to check ts-jest documentation. v7.0.0-alpha.2 uses the latest ts-jest which supports Babel 7.

**Comment by bcoe** [comment]
@marshallmick007 please reopen this issue if you're still having issues with `v7.0.0-alpha.2`.

**Comment by maddy619** [comment]
Please try setting sourceMap to true in test configuration of angular.json
