### ISSUE TITLE
Publish a new version of istanbul-lib-hook

### ISSUE THREAD

**Issue by serut** [istanbuljs/istanbuljs#143]
I'm not aware of your publish process, but if that's possible, can you release the master branch version of istanbul-lib-hook on npm ? The library I'm working on requires the changes that you made on #99. ¯\_(ツ)_/¯

**Comment by bcoe** [comment]
@serut could you please try `npm i istanbul-lib-hook@next` for me, and let me know if this version of the library does the trick for you?

**Comment by serut** [comment]
It's working nicely ! Thank you.
