### ISSUE TITLE
Please upgrade source-map to 0.7.2 to get speed improvements

### ISSUE THREAD

**Issue by andreicristianpetcu** [istanbuljs/istanbuljs#144]
The latest source-map which is v0.7.2 got support for WebAssembly and it is 10 times faster than the old one. More info here:

https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#072
http://fitzgeraldnick.com/2018/02/26/speed-without-wizardry.html
https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/
https://github.com/devtools-html/debugger.html/issues/5598

Please update so you would get 10 times speed improvements for your library in Firefox, 9 times in Safari and 5 times in Chrome.

**Comment by bcoe** [comment]
@andreicristianpetcu the new soure-map API is unfortunately async, which would require a fairly major refector of the Istanbul API to support:

https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#070

I'm open to help on this front, if you feel like taking a look. I can also look into whether it would be easier to update in nyc first (which has its own implementation of source-map handling).

**Comment by coreyfarrell** [comment]
@andreicristianpetcu Just want to mention I've upgraded source-map from 0.5 to 0.6 (in master, not yet released).  I didn't try updating to 0.7 because it says that it requires node.js 8 while node.js 6 isn't [EOL](https://github.com/nodejs/Release#release-schedule) for another 10 months.

**Comment by coreyfarrell** [comment]
I've looked into this and think it's impossible.  nyc needs to process source-map's during process exit hooks where code must be sync.  Unless a future version of source-map finds a way to support a sync API we will never be able to upgrade.
