### ISSUE TITLE
New ignoreClassMethods is now a required option property, breaking babel-plugin-istanbul

### ISSUE THREAD

**Issue by KylePDavis** [istanbuljs/istanbuljs#147]
In PR #127 `instanbul-lib-instrument` gained the ability to adds the ability to ignore class methods but the API for `programVisitor()` only provides a default value if the options object is omitted.

This means that now callers, such as `babel-plugin-istanbul` (here https://github.com/istanbuljs/babel-plugin-istanbul/blob/18fe954688fb4b9450138bf6f471446a88573133/src/index.js#L67-L70), who do not currently specify this new property to now start passing an empty array.

This should instead probably be defaulted if missing.

**Comment by coreyfarrell** [comment]
This was fixed as a side-effect of #200.
