### ISSUE TITLE
Add named anchors for code line numbers.

### ISSUE THREAD

**Issue by the-t-in-rtf** [istanbuljs/istanbuljs#148]
I put in [a pull against the "gitwarlost" repo](https://github.com/gotwarlost/istanbul/pull/787) before the move.  I'm resubmitting here.

The goal is to add named anchors to line numbers in coverage reports, similar to how line numbers work when viewing code on GitHub.  This would allow teams to link directly to lines of code within a code coverage report, which is helpful when discussing gaps, exclusions, et cetera.

**Comment by the-t-in-rtf** [comment]
I'm updating my previous pull to submit against the new repo.

**Comment by bcoe** [comment]
@the-t-in-rtf this should now be out the door 👍

**Comment by the-t-in-rtf** [comment]
Thanks, @bcoe.  Really glad to hear it.
