### ISSUE TITLE
istanbul-lib-hook 1.0.3 fails to install due to missing dependency

### ISSUE THREAD

**Issue by hniirane** [istanbuljs/istanbuljs#15]
I'm getting an error trying to install `istanbul-lib-hook@1.0.3` with the error:
```
npm ERR! notarget No compatible version found: append-transform@^0.4.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.4.0, 0.3.0, 0.2.2, 0.2.1, 0.2.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'istanbul-lib-hook'
```

This was originally due to my dependency on `jest-cli`. I see that the `append-transform@0.4.3` was tagged, but is not showing up in my `npm info append-transform` output.

**Comment by bcoe** [comment]
@hniirane this should have been fixed about 30 minutes ago when I rolled back the latest tag on istanbul-api; I've also now released `istanbul-lib-hook@1.0.4` which should fix the issue.

**Comment by hniirane** [comment]
@bcoe seems to work now, thanks for the quick fix! Some caches took time to update I guess. You can close the issue.

**Comment by bcoe** [comment]
@hniirane here's what happened if you're curious:

https://github.com/lerna/lerna/issues/698
