### ISSUE TITLE
Coverage is reported as 0 for files that have a default export that is an array definition

### ISSUE THREAD

**Issue by afenton90** [istanbuljs/istanbuljs#157]
**Do you want to request a _feature_ or report a _bug_?**

Coverage is reported as 0 for files that have a default export that is an array definition. For example.

```js
// actionsAB.js
import {
  actionA,
  actionB
} from '../../../actions';

export default [
  actionA,
  actionB
];
```

**What is the current behavior?**
Coverage for % Stmts | % Branch |  % Funcs |  % Lines is reported 0.

**If the current behavior is a bug, please provide the steps to reproduce and
either a repl.it demo through https://repl.it/languages/jest or a minimal
repository on GitHub that we can `yarn install` and `yarn test`.**

A simply test like this will reproduce it.
```js
import {
  actionA,
  actionB
} from '../../../actions';
import actions from './actionsAB.js';

test('has correct actions', () => {
  expect(actions).toEqual([
    actionA, 
    actionB
  ]);
});

```

**What is the expected behavior?**
100% coverage.

**Please provide your exact Jest configuration**
```js
const path = require('path');

module.exports = {
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.{js,jsx}'],
  coverageReporters: ['html', 'text'],
  coverageThreshold: {
    global: {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95
    }
  },
  setupFiles: [
    path.resolve(__dirname, 'test/shim.js')
  ],
  setupTestFrameworkScriptFile: path.resolve(__dirname, 'test/setup.js')
};

```

**Run `npx envinfo --preset jest` in your project directory and paste the
results here**

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 8.10.0
    Yarn: 1.5.1
    npm: 5.6.0
  npmPackages:
    jest:
      wanted: 22.x.x
      installed: 22.4.3
```

Originally raised here https://github.com/facebook/jest/issues/5917

**Comment by evanbb** [comment]
[Related](https://github.com/istanbuljs/babel-plugin-istanbul/issues/135)? Looks like code that simply `import`s and `export`s stuff doesn't get those statements instrumented...

**Comment by coreyfarrell** [comment]
Can you try again with the latest `jest`?  The version of jest you linked uses an older version of istanbul with babel 6, the current version of `jest` uses current istanbul with babel 7, so the situation may have changed.

**Comment by afenton90** [comment]
I can confirm that this is resolved with the latest version of `jest`. Thanks 👍
