### ISSUE TITLE
Support for class properties?

### ISSUE THREAD

**Issue by yassine** [istanbuljs/istanbuljs#164]
The 'istanbul-instrumenter-lib' module causes build crashes when instrumenting classes that define properties (including static ones).

While inspecting the issue, it seems that when parsing files by babel (through [babylon.parse](https://github.com/istanbuljs/istanbuljs/blob/ac824a46b25a815977394d96843a31657a2be77b/packages/istanbul-lib-instrument/src/instrumenter.js#L83)) the `classProperties` plugin isn't included.

Including the plugin to the `parse` call parameters seems to fix the parser issue at minimal effort, but still, the lines aren't processed as being within the scope of the coverage.

**Comment by coreyfarrell** [comment]
I have other commitments so I'm not able to look at this currently.  A minimum demo repository would be helpful for when I or someone else has time to look at this.

**Comment by coreyfarrell** [comment]
Support for configuring parse plugins was added by #948.  As for lines not being processed I can't help since no example code has been provided.

**Comment by gfortaine** [comment]
https://github.com/istanbuljs/istanbuljs/pull/356

It should be ready soon. The classProperties is now included, but commented, waiting for the release of node.js 12

**Comment by coreyfarrell** [comment]
classProperties and classPrivateProperties are now parsed by default and coverage is collected - #379.

This is published in nyc@14.1.0 to npm `next` tag.
