### ISSUE TITLE
Feature Request: Ability to Suppress Rows with Full Coverage in the Text Report

### ISSUE THREAD

**Issue by chrismohr** [istanbuljs/istanbuljs#169]
We're using jest in a project with a 100% coverage on most files, and I'd like to be able to focus in better on those few that don't. 

Maybe I could add a config option to `hideFull` or `skipFull` that works similarly to `skipEmpty`?

So, the expected output would be like this:
![hide_full](https://user-images.githubusercontent.com/601657/40282428-02605b0a-5c24-11e8-959e-cb111d534708.png)

Instead 100s of lines like this:
![current](https://user-images.githubusercontent.com/601657/40282432-16b38bfe-5c24-11e8-9d99-e7b916d4c4e4.png)

**Comment by JaKXz** [comment]
@chrismohr I think we can close this issue, these changes should have been released on npm. Let me know if not!

**Comment by ipwnponies** [comment]
How can I configure this? I'm not sure where `jest` is supposed to be looking for `skipFull` option.
