### ISSUE TITLE
Feature Request: Ability to mark what a test covers

### ISSUE THREAD

**Issue by sparkbuzz** [istanbuljs/istanbuljs#173]
With JS unit testing, it's easy to get false positives in coverage, and makes it difficult to audit which parts of source code doesn't have any explicit unit test coverage. For example, let's assume we have function a and b:

``` javascript
function b() { console.log('hello') }
function a() {  b(); }
```
and we test function **a**, we will get '_false positive_' coverage for **b**. Yes **b** was covered by a test, but it wasn't explicit.

It would be nice to be able to mark a unit test, using something like PHPUnit does to indicate what class, method, function or portion of code a unit test covers.

Take a a look at: https://phpunit.de/manual/3.7/en/appendixes.annotations.html#appendixes.annotations.covers for example.

If we can write for example a jest test like this:
``` javascript
describe('MyClass::myFunction', () => {
  /** @covers MyClass::myFunction **/
  it('does something amazing', () => {
    expect(MyClass::myFunction()).toDoSomethingAmazing();
  })
});

// or 

/** @coversModule 'src/reducers/hello' */
describe('...', () => {})
```

It might even be worth while implementing these above as JS decorators

``` javascript
@covers('something')
describe('...', () => {})
```

that would make a huge difference to be able to analyse a large code base and find source that hasn't been explicitly covered by a unit test.

Does anyone think that this is remotely possible as a feature?

**Comment by fgm** [comment]
There was an issue on that topic with additional details and suggestions on https://github.com/gotwarlost/istanbul/issues/159

**Comment by coreyfarrell** [comment]
This is not directly possible via istanbuljs or nyc as we have no concept of what a test is.  nyc has implemented a feature which allows test runners to override config per process.  This is used by `tap` which supports a concept of [coverage-maps](https://node-tap.org/docs/coverage/coverage-map/).  Note this functionality works on per-file boundaries only, it's not possible to restrict coverage further.

I'm closing this as out of scope for istanbuljs as it can only be implemented by the test runner.
