### ISSUE TITLE
Bug in istanbul-lib-hook@next found by nyc tests.

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#179]
I expected I'd be able to modify nyc:index.js `_handleJs` to work with the options argument instead of direct filename, but this was not the case.  I receive a failure on `nyc > wrap > wraps modules with coverage counters when they are required`.  After some digging I found that this is caused by the conversion of `options` to an object inside transformFn.  With some tracers I found that `nyc/test/fixtures/check-instrumented.js` is processed by the transform twice.  Prior to #99 it was only processed once as `shouldHook` was false in the second run because filename was already an object.

Testing:
* Run `git clone https://github.com/istanbuljs/nyc/ packages/nyc`.  This causes lerna to view nyc as if it were in the monorepo.
* Run `npm install` on the istanbuljs root so lerna will initialize dependencies for nyc.
* Modify `_handleJs` in packages/ by adding to the start of the function, forcing it to accept the new API:
```js
  if (typeof filename === 'object') {
    filename = filename.filename;
  }
```
* Run `npm test` from `packages/nyc`.  This will fail.
* `git revert 1504374` from istanbuljs.
* Retest nyc, it will succeed (it's ok to revert index.js or just leave it as is).

The crucial difference in 1504374 is that we were previously using the argument type to determine if we should run.  So if the argument type was not a string we skipped the transform.  It seems in some cases this was important to avoid instrumenting a source twice.

CC @bcoe @CodeTroopers @pangrr

**Comment by coreyfarrell** [comment]
Worth noting, `npm test` from the monorepo will not work, nyc fails even with 1504374 reverted.  I don't know if this is because of cross-env or lerna, or maybe even the fact nyc is used to run the lerna test.  Either way nyc testing has to be done directly from packages/nyc, the only reason I cloned it into the monorepo was to easily test it against istanbuljs HEAD.

**Comment by bcoe** [comment]
@coreyfarrell good digging, I'm glad we caught this before we promoted `next` to `latest`.  One thing I'm missing in your explanation, is how the heck does filename end up being an `object` the second time through instrumentation, vs., a filename?

would you like to submit a patch for this issue?

**Comment by coreyfarrell** [comment]
I just did a little more digging, the failing nyc test we get a call from `hookRequire` with a string filename.  The next call call via `hookRunInThisContext` has the object created by node.js `internal/modules/cjs/loader.js`.
