### ISSUE TITLE
Feature Request: Code markers as a by-pass for uncovered code

### ISSUE THREAD

**Issue by joewalker** [istanbuljs/istanbuljs#186]
The process of deciding if you have enough unit tests is somewhat ad-hoc. Many people don't aim for 100% and leave out "can't happen" cases.

I'd like to have markers in the code to say "it's OK if this code doesn't have coverage". That code doesn't count against your coverage score.

``` javascript
// Code called by unit tests
map.put("answer", 42);
// ...
const thing = map.get("answer");
if (thing == null) {
  // allow-uncovered-block
  throw new Error('Cant happen');
}
console.log(thing);
```

This function would show up as 100% covered (maybe with an asterisk to say "some lines excluded" or something)

Why?:

1. You don't need to continually re-evaluate the numbers in a coverage report - Instead, mark the file as `allow-uncovered-file` once and you're good.
2. You can enforce "100%" coverage as part of code acceptance criteria, and the uncovered sections are obvious during code review.
3. When refactoring some code, you have a marker to say "no test coverage", and can take that into account as you work.
4. IDEs could highlight uncovered code without running tests

**Comment by coreyfarrell** [comment]
This feature does exist, see https://github.com/istanbuljs/nyc/blob/master/README.md#parsing-hints-ignoring-lines

In the example code you'd want `/* istanbul ignore if */` before the if statement, that way it doesn't count the branch coverage either.

**Comment by joewalker** [comment]
Awesome, thanks!
