### ISSUE TITLE
Proposal: option to put __coverage__ on window.top (for iframes)

### ISSUE THREAD

**Issue by Lange** [istanbuljs/istanbuljs#199]
Hello! 👋 

### The Problem
I'm using `nyc` to gather code coverage for a web page which makes heavy use of iframes. In addition, it also makes heavy use of ShadowDOM. The end result is that the page has an unknown number of iframes in an unknown number of shadow roots. Crawling the entire page to discover each iframe is possible, but tedious and slow.

This is a problem, because it makes harvesting the `__coverage__` object from each iframe very difficult.

### The Solution
I would like to propose a way to tell `istanbul-lib-instrument` to always put coverage on [`window.top`](https://developer.mozilla.org/en-US/docs/Web/API/Window/top). This would ensure that I can always grab coverage from all of my iframes in one place, regardless of how many iframes there are and even if there are nested iframes.

It looks like [istanbul-lib-instrument/src/visitor.js#L485](https://github.com/istanbuljs/istanbuljs/blob/71b815d111af5181196173f8af94f14510bb5f7b/packages/istanbul-lib-instrument/src/visitor.js#L485) is where the current parent of the `__coverage__` object is defined, and would be where I'd need to implement this option.

I don't yet have a plan of attack, because I wanted to first see if such an option would be welcome as a Pull Request.

### Questions
1. Is my use case reasonable? Should `istanbul-lib-instrument` even try to support it?
2. Is my proposed solution reasonable?
3. Is there an alternative or simpler solution that I am unaware of?

Thanks for your time,
Alex

**Comment by Lange** [comment]
Upon further thought, I realized that a far simpler solution was available to me: perform a find-and-replace on my instrumented files before serving them.

Here's how I handled it for my use case: https://github.com/nodecg/nodecg/commit/119030b6f174f4bf0921afa97ef14033fbb1be8d

Cheers,
Alex

**Comment by coreyfarrell** [comment]
Actually I think it is a good idea for `istanbul-lib-instrument` to support this directly, it's not that difficult of a feature.  I have a patch in the works for this I will post when I get a chance to test it a bit.

**Comment by piyushrungta25** [comment]
Okay this is a bit embarrassing but how do I specify `coverageGlobalScope` option from `nyc` or the `babel-plugin-istanbul`? I tried putting it in `.nycrc` file without success.

**Comment by coreyfarrell** [comment]
No need to be embarrassed, this option has not yet been exposed in nyc or babel-plugin-istanbul.  I'm planning to add it and other options to babel-plugin-istanbul (https://github.com/istanbuljs/babel-plugin-istanbul/issues/208), just haven't had the cycles yet.

I hadn't planned on adding it to nyc but if it has a benefit I could be convinced.  If you wish to make that case please open a new ticket at https://github.com/istanbuljs/nyc/issues.

**Comment by piyushrungta25** [comment]
>  I'm planning to add it and other options to babel-plugin-istanbul (istanbuljs/babel-plugin-istanbul#208), just haven't had the cycles yet.

An idea when you would be taking this up? I can help with a PR if you are not planning on this soon.

> I hadn't planned on adding it to nyc

Any particular reason why this shouldn't be exposed in nyc? Looks like a pretty useful option when instrumenting code.

**Comment by coreyfarrell** [comment]
babel-plugin-istanbul needs to support browsers, nyc does not.  So I guess my reason against exposing this to nyc is that it's unneeded / adds complexity where I don't see any benefit.  As I said if benefit can be shown I could be convinced but I think starting in the babel plugin would be good.

I'd love a PR for the babel plugin, assuming the PR enables support for all appropriate options of istanbul-lib-instrument and not just these two.

Just so you are aware the istanbuljs org in the middle of a semver-major cycle for all modules.  Part of this is that the next version of babel-plugin-istanbul will be using [@istanbuljs/load-nyc-config](https://github.com/istanbuljs/load-nyc-config/) to load configuration, though that module is not yet released.
