### ISSUE TITLE
Weird issue with --coverage flag [jest]

### ISSUE THREAD

**Issue by k1r0s** [istanbuljs/istanbuljs#20]
https://github.com/facebook/jest/issues/3158

paste: 

--coverage opt broke my tests, why?

I have two scripts at my repo's package. https://github.com/k1r0s/kaop

```
    "test": "jest",
    "coverage": "jest --coverage",
```

´coverage´ fails but ´test´ runs as spected. Why?

**Comment by k1r0s** [comment]
![image](https://cloud.githubusercontent.com/assets/6052309/24329918/b74b612e-1213-11e7-81f1-4ea35e810518.png)

as you can see in the previous image `cov_13uk8uqqvg` variable isn't in my code.

Istanbul wraps functions in order to calculate coverage, but broke my tests

**Comment by bcoe** [comment]
@k1r0s reading the original thread; it sounds like the underlying issue was an eval statement?

This sounds like something we should support on our end?

**Comment by k1r0s** [comment]
for sure

**Comment by k1r0s** [comment]
If you want more info about check this commit 

https://github.com/k1r0s/kaop/commit/a553a6dd41d23868811f2a1754933f09d48bfe9b

I think no code instrument api can support that scenario...

my library is magic
