### ISSUE TITLE
named functions not covered if locally scoped variable of same name exists

### ISSUE THREAD

**Issue by indieisaconcept** [istanbuljs/istanbuljs#267]
Took me a while to figure out what was actually going on but I've discovered an issue whereby a locally scoped variable which has the same name as the enclosing parent function results in coverage not being generated for that function.

## Expected Behavior

Coverage report generated for all files under test.

## Observed Behavior

Not all files are reported

## Bonus Points! Code (or Repository) that Reproduces Issue

Here is a contrived example and project.

```JavaScript
module.exports = function sum (...args) {

    let sum = args.reduce((acc, value) => {
        acc += value;
        return acc;
    }, 0);

    return sum;
};
```

https://github.com/indieisaconcept/istanbul-issue-example

## Forensic Information

**Operating System:** : OSX 10.12.3
**Environment Information:** [indieisaconcept/a793194bd7a31ea1905a0b92c43c10f3](https://gist.github.com/indieisaconcept/a793194bd7a31ea1905a0b92c43c10f3)

**Comment by coreyfarrell** [comment]
I'm not sure when but it appears this issue has been fixed.  I tested your repo and did not get any results for `broken.js`.  I then upgraded nyc to 13.3.0 and retested, this produced the expected results for `broken.js`.  Possibly this is related to our upgrade from babel 6 to babel 7.
