### ISSUE TITLE
Is it possible to suppress "nothing could be mapped" errors?

### ISSUE THREAD

**Issue by ben-eb** [istanbuljs/istanbuljs#27]
> Could I convince to reopen this issue on the istanbuljs monorepo?

Done.

https://github.com/istanbuljs-archived-repos/istanbul-lib-source-maps/issues/9

**Comment by bcoe** [comment]
@ben-eb thank you! what if we did something like made:

https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/transformer.js#L169

Only output the warning if a `DEBUG` environment variable is set? `ISTANBUL_DEBUG`? Is there an existing convention we can borrow from?

**Comment by ben-eb** [comment]
How about https://github.com/visionmedia/debug?
