### ISSUE TITLE
Proposal: New highlighting pattern for HTML report

### ISSUE THREAD

**Issue by takuyahara** [istanbuljs/istanbuljs#277]
Hello folks. I feel the HTML report I got highlights code weirdly. I wrote a report about how code highlighting is done in various environment and how it should be in my personal opinion and also how to fix in two styles. I just did as a hack but if it is useful I may send a PR. Please let me know your thoughts and I hope it is helpful.

# My report and opinion
## Screenshot
![0_d0er_yw9jc7ump4t](https://user-images.githubusercontent.com/46240835/51342057-2f46bf80-1ad6-11e9-997b-122563045b88.png)

## Detail
[IstanbulJS generates weirdly highlighted HTML report](https://medium.com/@TakuyaHARA/istanbuljs-generates-weirdly-highlighted-html-report-f233ff5cfead)

# Proposal 1
## Screenshot
![0_t_edszj6fw0anf-k](https://user-images.githubusercontent.com/46240835/51342067-37066400-1ad6-11e9-8419-beba2b7c8259.png)

## Detail
[Fix IstanbulJS — Proposal 1](https://medium.com/@TakuyaHARA/fix-istanbuljs-proposal-1-35db1693e455)

# Proposal2 
## Screenshot
![screencapture-takuyahara-github-io-share-20190104_istanbuljs_coverage_issue-11_solutionb-typescript_v1-coverage-2_function-0_normal-classmethod-tsx-html-2019-01-18-00_27_46](https://user-images.githubusercontent.com/46240835/51342087-45ed1680-1ad6-11e9-8bd4-2b89191c4233.png)

## Detail
[Fix IstanbulJS — Proposal 2](https://medium.com/@TakuyaHARA/fix-istanbuljs-proposal-2-c0f3fb8f3592)

**Comment by coreyfarrell** [comment]
Your links to medium reference an older version of istanbul-lib-instrument.  To look into this further we would need to know that the problem exists in the most current versions of all istanbuljs packages.  istanbuljs/nyc#972 is a ticket we're using to track progress publishing an updated release of everything.  I suspect some of the issues you've shown in these images could be source-map related, the next release of nyc will include some fixes to this.

**Comment by coreyfarrell** [comment]
@takuyahara is this still an issue?

**Comment by takuyahara** [comment]
No, I close this. Thank you.
