### ISSUE TITLE
NYC doesn't work correctly with local node_modules

### ISSUE THREAD

**Issue by hershmire** [istanbuljs/istanbuljs#278]
## Expected Behavior

NYC to not exclude local node_modules (i.e. `src/node_modules/...` OR `src/somedirectory/node_modules/**`) BUT to exclude root node_modules. We have a lot of Node applications at the company I work for that use the pattern of creating local node_modules as it helps modularize our code at an application/page-level and provides a nice way to require files instead of doing long relative paths to everything. Below is an example file structure many of our apps could see:

```
app/
  |- node_modules/ (root modules and we expect to exclude)
  |- src/
  |  |- node_modules/ (local to the app)
  |  |  |- local-module-1/
  |  |  |  |- test-node/
  |  |  |  |  |- file-test.js
  |  |  |  |- package.json
  |  |  |  |- file.js
  |  |- middleware
  |  |- pages/
  |  |  |- page-1/
  |  |  |  |- test-node/
  |  |  |  |  |- file-test.js
  |  |  |- file.js
  |  |  |  |- node_modules/ (local to page 1 of application)
  |  |  |  |  |- page-local-module-1/
  |  |  |  |  |  |- test-node/
  |  |  |  |  |  |  |- file-test.js
  |  |  |  |  |  |- package.json
  |  |  |  |  |  |- file.js
  |  |  |- page-2/
  ...
```

## Observed Behavior

Since by default, NYC adds the glob `**/node_modules/**` it will exclude all node_modules, which in our case we don't want. To get around this problem, you have a negateExcludes section where we supply `!src/**/node_modules/**` but that doesn't quite work right as it will force to include our test files which live next to the files that are being tested since negateExclude is evaluated after the exclude rules.

Additionally, even with the `all: true` flag set in package.json, NYC doesn't appear to be picking up all files as I thought it would; especially the ones that I purposely left out of having tests point to – i.e. https://github.com/hershmire/nyc-test/blob/master/src/pages/page-1/components/Name.jsx & https://github.com/hershmire/nyc-test/tree/master/src/pages/page-no-tests-1.

It would be nice to not exclude all node_modules by default but just the root ones for starters. OR at least provide a easier way to turn that off. It gets quite complicated when you also have to take into account babel-plugin-istanbul and understand how to set both up properly.

## Bonus Points! Code (or Repository) that Reproduces Issue

I created a quick demo app that shows what I'm running into here:

https://github.com/hershmire/nyc-test

After running `yarn install`, run `yarn coverage`

As you can see from the results, my test files under any `test-node` folders are picked up which they should be excluded.

![screen shot 2018-08-06 at 13 33 33](https://user-images.githubusercontent.com/757524/43740748-05c96f44-9981-11e8-8adf-533a579d39fa.png)

## Forensic Information

**Operating System:** the operating system you observed the issue on.
MacOS 10.13.6

**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

https://github.com/hershmire/nyc-test/blob/master/output.txt

**Comment by bcoe** [comment]
:wave: I've moved this issue to the istanbuljs repo, I think we should address this behavior in `test-exclude` if possible.

**Comment by coreyfarrell** [comment]
With the merge of #213, #351, istanbuljs/nyc#912 and istanbuljs/nyc#1053 this is now supported in nyc, documented by istanbuljs/nyc#1039.  To get this feature you need to upgrade to nyc@14.0.0.

istanbuljs/babel-plugin-istanbul#172 still pending, need to resolve a merge conflict.  Further progress can be monitored on that PR if you need this functionality in the babel plugin.
