### ISSUE TITLE
html reporter not working

### ISSUE THREAD

**Issue by Stupidism** [istanbuljs/istanbuljs#28]
```
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'xxxx/node_modules/nyc/node_modules/istanbul-reports/lib/html/assets'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)

```

**Comment by bcoe** [comment]
@Stupidism could you share a project (or a branch of a project) that is exhibiting this issue?

I haven't been able to reproduce on my own projects, which makes me think there must ben an edge-case that's triggering this behavior.

**Comment by Stupidism** [comment]
Wierd, it's gone in my project. It must be an occasional bug.

**Comment by Stupidism** [comment]
It happens again, here is my detailed tests:
## commands
- A: npm run test:cover
- B-G(global): nyc report --reporter=html
- B-L(local): ./node_modules/.bin/nyc report --reporter=html
- C(npm scripts): A && B-G

| install tool        | npm           | yarn  |
| ------------- |:-------------:| -----:|
| run `A` and then `B-G`   | working | working |
| run `A` and then `B-L`      | working      |   working |
| run `A && B-G`      | working      |   working |
| run `A && B-L`      | working      |   error |
| run `C`      | working      |   error |

**Comment by Stupidism** [comment]
Not sure this is a problem with `yarn` or `istanbul`
Possible reasons:
1. `yarn` has a bug
2. `istanbul` used some not-fullly-supported-by-yarn hook of npm.

**Comment by Stupidism** [comment]
@bcoe updates

**Comment by bcoe** [comment]
@Stupidism it sounds like this was an issue with yarn, that may have been resolved; mind testing things out with the latest version?

**Comment by bcoe** [comment]
@Stupidism I dug into this problem a bit further for you, the problem is the order of the rewire and istanbul plugin:

https://github.com/speedskater/babel-plugin-rewire#istanbul

If you swap the order of istanbul, and rewire in @JaKXz's example configuration, things should start working for you.

**Comment by Stupidism** [comment]
Not fixed yet! @bcoe

**Comment by bcoe** [comment]
@Stupidism I've tested @JaKXz's branch of your repo; if you switch the order of rewire and istanbul things should start working for you.

**Comment by Stupidism** [comment]
Have you tried these three cmds?
```

yarn remove nyc
yarn clean
yarn add --dev nyc
```

**Comment by bcoe** [comment]
@Stupidism no, but it sounded like there was a known issue with yarn deleting a required folder that was fixed in newer versions; @JaKXz can you speak to this?

**Comment by Stupidism** [comment]
Yeah, I guess it's a bug caused by `yarn`. I will watch that [thread](https://github.com/yarnpkg/yarn/issues/3056#issuecomment-294266971) in yarn repo
