### ISSUE TITLE
Configuration option to include function headers as part of coverage (as Istanbul does)

### ISSUE THREAD

**Issue by Rush** [istanbuljs/istanbuljs#285]
Below is a screenshot showing a difference between lcov reports from istanbul and nyc. I am trying to migrate from istanbul but in order to safely do so I would preferably like to see same coverage numbers.  
My request is about ability to reproduce istanbul behavior in nyc.

![](https://rush.sh/dojgD12n6pMKslxq7UFXTzYZr7Y/istanbul-vs-nyc.png)

Note, I am not the only one suffering from this issue as proven by this problem reported to Codecov  https://github.com/codecov/support/issues/391

Many thanks for the great tool which is nyc!

**Comment by coreyfarrell** [comment]
> I note that it does highlight the line if the function is assigned

In this case it's not actually highlighting because of the function declaration, it's highlighting because of the assignment expression.

**Comment by coreyfarrell** [comment]
@Rush I appreciate this report however exact replication of coverage from the legacy `istanbul` tool is not a goal.  I believe the current coverage is correct, function headers are not actually run.
