### ISSUE TITLE
jest failing with coverage flag `with statement`

### ISSUE THREAD

**Issue by dhaval-lila** [istanbuljs/istanbuljs#288]
I am running jest for code coverage and few tests are failing with error thrown as `with in strict mode`. I know that with statement is coming from below jest transformer in my code base
```
require('ejs-loader');
const _ = require('lodash');

module.exports = {
  process(src) {
    console.log(`module.exports = ${_.template(src)}`);
    return `module.exports = ${_.template(src)}`;
  },
};
```
but the question is why test aren't failing when jest runs without `--coverage` and only fails with `--coverage`? all my `"use strict"` are functional scoped and `${_.template(src)}` doesn't put the strict in function so from where this global `"use strict"` is coming from? my guess is istanbul is somehow putting global `"use strict"` is it right?  and if it is how can i disable it?

**Comment by JaKXz** [comment]
Since jest doesn't use nyc but the internals from the istanbuljs monorepo I transferred the issue to the right place

**Comment by laytong** [comment]
Looks to me like I'm having the same problem.

@dhaval-lila did you ever get to the bottom of this?

**Comment by coreyfarrell** [comment]
@SimenB it looks like jest uses `babel-plugin-istanbul` to instrument, how is babel config determined?  Specifically it seems like some of your users might need `sourceType: 'script'`, see https://babeljs.io/docs/en/options#sourcetype.  For them the issue with the default `module` is that it forbids non-strict code.

@laytong @dhaval-lila a link to a repository showing the issue would probably be helpful.

**Comment by SimenB** [comment]
Babel config is loaded via `@babel/core`'s `loadPartialConfig`: https://github.com/facebook/jest/blob/9595efa8b5a063823ecd39cffdabf16bb10508ef/packages/babel-jest/src/index.ts#L46-L64

**Comment by coreyfarrell** [comment]
If I'm understanding correctly I suspect this issue can be resolved by the users providing a babel config (.babelrc or babel.config.js) which includes the following:
```js
{
  "sourceType": "script"
}
```

**Comment by laytong** [comment]
Hmm. . .So far i've been unsuccessful in trying to recreate the behaviour in a small repo. I'll keep at it.

Adding `sourceType: script` is a no go for us.

**Comment by coreyfarrell** [comment]
The default for `sourceType` is `module`, this enforces strict mode.  See https://babeljs.io/docs/en/options#sourcetype.  See also from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with#Description:
> Using with is not recommended, and is forbidden in ECMAScript 5 strict mode

So if `sourceType: module` applies then it is expected that `with` statements will throw an error.  You might try `sourceType: unambiguous` if you have some sources that are ES modules but others that are non-strict ES5.  The error is from the babel parser which needs to know if a file without `use strict` is a non-strict script/CJS or a strict-by-default ES module.

Also just noticed @SimenB comment about jest@23.  For anyone experiencing this issue if you are using jest@23 please upgrade to jest@24.  jest@23 uses an older version of istanbul libraries based on babel 6, I'm unable to provide support for that.

**Comment by laytong** [comment]
For posterity in case this helps anyone else. I blew away my yarn.lock and generated a new one. Looks like some combination of janky yarn sub-dependencies seemed to be the culprit for me

**Comment by coreyfarrell** [comment]
I'm closing this since it seems to be resolved for @laytong and we have not gotten further comment from @dhaval-lila.
