### ISSUE TITLE
handlebars dependency in istanbul-reports needs to be updated

### ISSUE THREAD

**Issue by nbj** [istanbuljs/istanbuljs#293]
As of Feb. 14th 2019 istanbul-reports is broken due to vulnerability in the dependency of handlebars.

See: https://www.npmjs.com/advisories/755

This should be an easy fix, alas I was not allowed to push a PR.

**Comment by nbj** [comment]
I can see a PR has been made, but it is in a broken state. A fix would be much appreciated, as our CI depends on this working :)

**Comment by nbj** [comment]
@YuriGor has made a PR: #294 

Looking forward to getting it tagged :)

**Comment by coreyfarrell** [comment]
Please be patient.  I appreciate the trouble you are having in CI but istanbul / nyc has no full-time/paid staff, just a few main people who volunteer time to help maintain this project.

I'm just now seeing this issue and have merged the update to istanbul-reports (it's 8AM local time for me).

**Comment by coreyfarrell** [comment]
Updated istanbul libraries are now published.  It'll take me a bit longer to get an update to nyc published (ref istanbuljs/nyc#991).
