### ISSUE TITLE
How to cover jsx syntax in js files?

### ISSUE THREAD

**Issue by Stupidism** [istanbuljs/istanbuljs#30]
I think the coverage rate here is right, but it seems the red color is wrong.

![image](https://cloud.githubusercontent.com/assets/5801015/24774744/eecb938a-1ace-11e7-8347-417c71820b38.png)
Way to reproduce:
```
git clone git@github.com:Stupidism/react-starter-kit.git -b feat/test-coverage
cd react-starter-kit
yarn install 
yarn run coverage 
```

**Comment by Stupidism** [comment]
The colors and number beside line number are right.
Color mask covered on code seems to have right start but wrong end.
So it's not that buggy for me.

**Comment by bcoe** [comment]
@Stupidism @JaKXz see: https://github.com/speedskater/babel-plugin-rewire#istanbul

This bug should be fixed once rewire and istanbul are used in the appropriate order.

**Comment by Stupidism** [comment]
This is fixed @bcoe Thank you very much!
