### ISSUE TITLE
Explore deprecation of istanbul-api

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#321]
I'd like for us to consider deprecating `istanbul-api` in favor of consumers directly using the implementation modules (`istanbul-lib-report`, etc).  The motivation is `source-map@0.7.3` - the async constructor requires breaking API changes to `istanbul-lib-source-maps` and I'm not sure how to make `istanbul-api` work with it.  One idea I have is to publish `istanbul-api@3.0.0` and immediate deprecate that version only.  This way we discourage new modules from using istanbul-api but we don't cause a deprecation warning for the existing major users.  When we drop node.js 6 and upgrade `source-map` we would not update `istanbul-api` to be compatible.

According to npmjs.com `istanbul-api` was downloaded 5.1 million times last week.  `jest-cli` was downloaded 4.5 million times.  `jest-cli` is being split up so the `istanbul-api` dependency is moving to `@jest/reporters`.  `createReporter` is the only thing jest uses from `istanbul-api` so I'm hoping we can convince them to use `istanbul-lib-report` directly.

Another large user is `karma-coverage-istanbul-reporter` at 700k downloads last week.  `fusion-cli` had 15k last week, I'm not seeing any other dependents with a large number of downloads.

About the missing 200k `istanbul-api` downloads, I'm guessing `jest-cli@14` and below is still getting significant downloads, that version uses the original `istanbul` module.

**Comment by bcoe** [comment]
@SimenB could I get your thoughts on this topic?

**Comment by SimenB** [comment]
Hey! 👋
Happy to switch to using whatever API you want Jest to use (preferably via a PR 😀)

**Comment by coreyfarrell** [comment]
@SimenB I could give it a shot.  I've run `yarn && yarn test` almost successfully.  A couple tests failed with messages about `hg` which surprising since I do have `hg` installed (sorry I lost the scrollback log for the error).  Doesn't matter though I've established baseline for test results on my system.  The things I need to know:
* When I edit `packages/jest-reporters/src/coverage_reporter.ts`, how do I rebuild jest-reporters only?
* How can I run jest-reporters tests only?

Obviously when I think I have a functional change I'll expand my testing to everything but I need to be able to run more focused tests initially.

**Comment by SimenB** [comment]
> A couple tests failed with messages about hg which surprising since I do have hg installed (sorry I lost the scrollback log for the error).

The `hg` tests were fixed just a couple of days ago (https://github.com/facebook/jest/pull/8066), so in theory refreshing your fork should do it. If not, I'll take a look!

>When I edit packages/jest-reporters/src/coverage_reporter.ts, how do I rebuild jest-reporters only?

You should run `yarn watch`, it will first build everything, then start a watcher that only rebuilds the files that changes. You might want to run `yarn watch:ts` in a separate terminal to get typechecks in watch mode as well (make sure to run it after the initial build done by `yarn watch` so it doesn't rebuild everything)

If you've already built everything, you can also do `node scripts/watch.js` to start the watcher.

>How can I run jest-reporters tests only?

By doing `yarn jest packages/jest-reporters (--watch)` from the root of the repo. You'll probably want `yarn jest coverage reporters (--watch)` at some point to also run the integration tests 🙂

**Comment by coreyfarrell** [comment]
@SimenB I think I have the correct code in place for jest-reporters, having an issue with typescript checking.
```
packages/jest-reporters/src/coverage_reporter.ts:102:43 - error TS2345: Argument of type 'string' is not assignable to parameter of type '"none" | "text-summary" | "clover" | "cobertura" | "html" | "json" | "json-summary" | "lcov" | "lcovonly" | "teamcity" | "text" | "text-lcov"'.

102         tree.visit(istanbulReports.create(_reporter, {}), reportContext);
                                              ~~~~~~~~~

packages/jest-cli/src/cli/index.ts:14:22 - error TS2307: Cannot find module '@jest/core'.
```

It seems that `@types/istanbul-report` declares the specific values which can be used.  The broken branch is at https://github.com/coreyfarrell/jest/tree/reports-next.  Note that I have no idea what to do about `packages/jest-reporters/src/__tests__/coverage_reporter.test.js`.  For now I've just deleted that file.

**Comment by coreyfarrell** [comment]
The above happened when I ran `yarn` from a clean working copy.

**Comment by SimenB** [comment]
@coreyfarrell I'd love to chat about these things.  Do we have some Istanbul chat? Like slack, discord etc? If not, wanna join Jest's? It's part of Reactiflux

**Comment by coreyfarrell** [comment]
@SimenB we have slack, you can join at http://devtoolscommunity.herokuapp.com/ (the actual slack is https://node-tooling.slack.com/ channel `#istanbuljs`).  If that's trouble I could join jest, just let me know where to go.
