### ISSUE TITLE
Handle generated position of 0 in istanbul-lib-source-maps

### ISSUE THREAD

**Issue by dicarlo2** [istanbuljs/istanbuljs#330]
I'm running into the following error when remapping:
```
/private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/source-map/lib/source-map-consumer.js:588
      throw new TypeError('Column must be greater than or equal to 0, got '
            ^
TypeError: Column must be greater than or equal to 0, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/source-map/lib/source-map-consumer.js:588:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/source-map/lib/source-map-consumer.js:653:22)
    at originalEndPositionFor (/private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/istanbul-lib-source-maps/lib/transformer.js:46:38)
    at getMapping (/private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/istanbul-lib-source-maps/lib/transformer.js:105:15)
    at /private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/istanbul-lib-source-maps/lib/transformer.js:207:23
    at Array.forEach (<anonymous>)
    at SourceMapTransformer.processFile (/private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/istanbul-lib-source-maps/lib/transformer.js:196:31)
    at /private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/istanbul-lib-source-maps/lib/transformer.js:255:24
    at Array.forEach (<anonymous>)
    at SourceMapTransformer.transform (/private/var/tmp/_bazel_dicarlo/3d230d9ceea84cb22d33c0b1ff575fab/execroot/neotracker/bazel-out/darwin-fastbuild/bin/ts/client/__tests__/env.runfiles/npm/node_modules/istanbul-lib-source-maps/lib/transformer.js:245:25)
```

It appears to boil down to `generatedEnd.column === 0`, which makes it an invalid column when we try to find the beforeEnd/afterEnd mappings here: https://github.com/istanbuljs/istanbuljs/blob/03d1a522a71aa16cdf5211aa26481a68dad7aeb9/packages/istanbul-lib-source-maps/lib/get-mapping.js#L33-L36 While I'm not certain that this isn't a bug in how we are generating source maps, I would still suggest either:

1. Change the above line to `generatedEnd.column === 0 ? 0 : generatedEnd.column - 1`.
2. Change `isInvalidPosition` check to include 0, i.e. `generatedEnd.column <= 0`: https://github.com/istanbuljs/istanbuljs/blob/03d1a522a71aa16cdf5211aa26481a68dad7aeb9/packages/istanbul-lib-source-maps/lib/get-mapping.js#L73-L81

**Comment by coreyfarrell** [comment]
source-maps are difficult, could you link us to a repository that reproduces this error?

**Comment by dicarlo2** [comment]
@coreyfarrell unfortunately it's an internal repo that uses some fairly custom bazel machinery to hook everything up. I'm not sure that I'll be able to make a small repro repo without pulling in a bunch of our internal code.

I can provide the offending file (with source map) though: 
```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable */
// @ts-ignore
const defaultResolver_1 = __importDefault(require("jest-resolve/build/defaultResolver"));
function resolve(path, options) {
    let res = () => require.resolve(path);
    let otherResolve = () => defaultResolver_1.default(path, options);
    if (path.startsWith('.')) {
        res = otherResolve;
        otherResolve = () => require.resolve(path);
    }
    try {
        return res();
    }
    catch (_a) {
        return otherResolve();
    }
}
module.exports = resolve;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVzb2x2ZUplc3RNb2R1bGUuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi90cy9zY3JpcHRzL2plc3QvcmVzb2x2ZUplc3RNb2R1bGUudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7QUFBQSxvQkFBb0I7QUFDcEIsYUFBYTtBQUNiLHlGQUFpRTtBQUVqRSxTQUFTLE9BQU8sQ0FBQyxJQUFZLEVBQUUsT0FBWTtJQUN6QyxJQUFJLEdBQUcsR0FBRyxHQUFHLEVBQUUsQ0FBQyxPQUFPLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDO0lBQ3RDLElBQUksWUFBWSxHQUFHLEdBQUcsRUFBRSxDQUFDLHlCQUFlLENBQUMsSUFBSSxFQUFFLE9BQU8sQ0FBQyxDQUFDO0lBQ3hELElBQUksSUFBSSxDQUFDLFVBQVUsQ0FBQyxHQUFHLENBQUMsRUFBRTtRQUN4QixHQUFHLEdBQUcsWUFBWSxDQUFDO1FBQ25CLFlBQVksR0FBRyxHQUFHLEVBQUUsQ0FBQyxPQUFPLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDO0tBQzVDO0lBRUQsSUFBSTtRQUNGLE9BQU8sR0FBRyxFQUFFLENBQUM7S0FDZDtJQUFDLFdBQU07UUFDTixPQUFPLFlBQVksRUFBRSxDQUFDO0tBQ3ZCO0FBQ0gsQ0FBQztBQUVELE1BQU0sQ0FBQyxPQUFPLEdBQUcsT0FBTyxDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiLyogZXNsaW50LWRpc2FibGUgKi9cbi8vIEB0cy1pZ25vcmVcbmltcG9ydCBkZWZhdWx0UmVzb2x2ZXIgZnJvbSAnamVzdC1yZXNvbHZlL2J1aWxkL2RlZmF1bHRSZXNvbHZlcic7XG5cbmZ1bmN0aW9uIHJlc29sdmUocGF0aDogc3RyaW5nLCBvcHRpb25zOiBhbnkpOiBhbnkge1xuICBsZXQgcmVzID0gKCkgPT4gcmVxdWlyZS5yZXNvbHZlKHBhdGgpO1xuICBsZXQgb3RoZXJSZXNvbHZlID0gKCkgPT4gZGVmYXVsdFJlc29sdmVyKHBhdGgsIG9wdGlvbnMpO1xuICBpZiAocGF0aC5zdGFydHNXaXRoKCcuJykpIHtcbiAgICByZXMgPSBvdGhlclJlc29sdmU7XG4gICAgb3RoZXJSZXNvbHZlID0gKCkgPT4gcmVxdWlyZS5yZXNvbHZlKHBhdGgpO1xuICB9XG5cbiAgdHJ5IHtcbiAgICByZXR1cm4gcmVzKCk7XG4gIH0gY2F0Y2gge1xuICAgIHJldHVybiBvdGhlclJlc29sdmUoKTtcbiAgfVxufVxuXG5tb2R1bGUuZXhwb3J0cyA9IHJlc29sdmU7XG4iXX0=
```

Sticking that into [https://sokra.github.io/source-map-visualization/#custom](https://sokra.github.io/source-map-visualization/#base64,InVzZSBzdHJpY3QiOwp2YXIgX19pbXBvcnREZWZhdWx0ID0gKHRoaXMgJiYgdGhpcy5fX2ltcG9ydERlZmF1bHQpIHx8IGZ1bmN0aW9uIChtb2QpIHsKICAgIHJldHVybiAobW9kICYmIG1vZC5fX2VzTW9kdWxlKSA/IG1vZCA6IHsgImRlZmF1bHQiOiBtb2QgfTsKfTsKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgeyB2YWx1ZTogdHJ1ZSB9KTsKLyogZXNsaW50LWRpc2FibGUgKi8KLy8gQHRzLWlnbm9yZQpjb25zdCBkZWZhdWx0UmVzb2x2ZXJfMSA9IF9faW1wb3J0RGVmYXVsdChyZXF1aXJlKCJqZXN0LXJlc29sdmUvYnVpbGQvZGVmYXVsdFJlc29sdmVyIikpOwpmdW5jdGlvbiByZXNvbHZlKHBhdGgsIG9wdGlvbnMpIHsKICAgIGxldCByZXMgPSAoKSA9PiByZXF1aXJlLnJlc29sdmUocGF0aCk7CiAgICBsZXQgb3RoZXJSZXNvbHZlID0gKCkgPT4gZGVmYXVsdFJlc29sdmVyXzEuZGVmYXVsdChwYXRoLCBvcHRpb25zKTsKICAgIGlmIChwYXRoLnN0YXJ0c1dpdGgoJy4nKSkgewogICAgICAgIHJlcyA9IG90aGVyUmVzb2x2ZTsKICAgICAgICBvdGhlclJlc29sdmUgPSAoKSA9PiByZXF1aXJlLnJlc29sdmUocGF0aCk7CiAgICB9CiAgICB0cnkgewogICAgICAgIHJldHVybiByZXMoKTsKICAgIH0KICAgIGNhdGNoIChfYSkgewogICAgICAgIHJldHVybiBvdGhlclJlc29sdmUoKTsKICAgIH0KfQptb2R1bGUuZXhwb3J0cyA9IHJlc29sdmU7Ci8qIGJhc2U2NCBzb3VyY2UgbWFwIHJlbW92ZWQgKi8=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVzb2x2ZUplc3RNb2R1bGUuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi90cy9zY3JpcHRzL2plc3QvcmVzb2x2ZUplc3RNb2R1bGUudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7QUFBQSxvQkFBb0I7QUFDcEIsYUFBYTtBQUNiLHlGQUFpRTtBQUVqRSxTQUFTLE9BQU8sQ0FBQyxJQUFZLEVBQUUsT0FBWTtJQUN6QyxJQUFJLEdBQUcsR0FBRyxHQUFHLEVBQUUsQ0FBQyxPQUFPLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDO0lBQ3RDLElBQUksWUFBWSxHQUFHLEdBQUcsRUFBRSxDQUFDLHlCQUFlLENBQUMsSUFBSSxFQUFFLE9BQU8sQ0FBQyxDQUFDO0lBQ3hELElBQUksSUFBSSxDQUFDLFVBQVUsQ0FBQyxHQUFHLENBQUMsRUFBRTtRQUN4QixHQUFHLEdBQUcsWUFBWSxDQUFDO1FBQ25CLFlBQVksR0FBRyxHQUFHLEVBQUUsQ0FBQyxPQUFPLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxDQUFDO0tBQzVDO0lBRUQsSUFBSTtRQUNGLE9BQU8sR0FBRyxFQUFFLENBQUM7S0FDZDtJQUFDLFdBQU07UUFDTixPQUFPLFlBQVksRUFBRSxDQUFDO0tBQ3ZCO0FBQ0gsQ0FBQztBQUVELE1BQU0sQ0FBQyxPQUFPLEdBQUcsT0FBTyxDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiLyogZXNsaW50LWRpc2FibGUgKi9cbi8vIEB0cy1pZ25vcmVcbmltcG9ydCBkZWZhdWx0UmVzb2x2ZXIgZnJvbSAnamVzdC1yZXNvbHZlL2J1aWxkL2RlZmF1bHRSZXNvbHZlcic7XG5cbmZ1bmN0aW9uIHJlc29sdmUocGF0aDogc3RyaW5nLCBvcHRpb25zOiBhbnkpOiBhbnkge1xuICBsZXQgcmVzID0gKCkgPT4gcmVxdWlyZS5yZXNvbHZlKHBhdGgpO1xuICBsZXQgb3RoZXJSZXNvbHZlID0gKCkgPT4gZGVmYXVsdFJlc29sdmVyKHBhdGgsIG9wdGlvbnMpO1xuICBpZiAocGF0aC5zdGFydHNXaXRoKCcuJykpIHtcbiAgICByZXMgPSBvdGhlclJlc29sdmU7XG4gICAgb3RoZXJSZXNvbHZlID0gKCkgPT4gcmVxdWlyZS5yZXNvbHZlKHBhdGgpO1xuICB9XG5cbiAgdHJ5IHtcbiAgICByZXR1cm4gcmVzKCk7XG4gIH0gY2F0Y2gge1xuICAgIHJldHVybiBvdGhlclJlc29sdmUoKTtcbiAgfVxufVxuXG5tb2R1bGUuZXhwb3J0cyA9IHJlc29sdmU7XG4iXX0=,LyogZXNsaW50LWRpc2FibGUgKi8KLy8gQHRzLWlnbm9yZQppbXBvcnQgZGVmYXVsdFJlc29sdmVyIGZyb20gJ2plc3QtcmVzb2x2ZS9idWlsZC9kZWZhdWx0UmVzb2x2ZXInOwoKZnVuY3Rpb24gcmVzb2x2ZShwYXRoOiBzdHJpbmcsIG9wdGlvbnM6IGFueSk6IGFueSB7CiAgbGV0IHJlcyA9ICgpID0+IHJlcXVpcmUucmVzb2x2ZShwYXRoKTsKICBsZXQgb3RoZXJSZXNvbHZlID0gKCkgPT4gZGVmYXVsdFJlc29sdmVyKHBhdGgsIG9wdGlvbnMpOwogIGlmIChwYXRoLnN0YXJ0c1dpdGgoJy4nKSkgewogICAgcmVzID0gb3RoZXJSZXNvbHZlOwogICAgb3RoZXJSZXNvbHZlID0gKCkgPT4gcmVxdWlyZS5yZXNvbHZlKHBhdGgpOwogIH0KCiAgdHJ5IHsKICAgIHJldHVybiByZXMoKTsKICB9IGNhdGNoIHsKICAgIHJldHVybiBvdGhlclJlc29sdmUoKTsKICB9Cn0KCm1vZHVsZS5leHBvcnRzID0gcmVzb2x2ZTsK) and nothing really looks out of the ordinary.

**Comment by coreyfarrell** [comment]
#375 fixed some source-map issues, can you retest with latest versions?

**Comment by dicarlo2** [comment]
@coreyfarrell not sure if it was #375 or not, but we're not running into this issue anymore, thanks for following up though!
