### ISSUE TITLE
istanbul-lib-instrument: Add `bigInt` to default babel parser plugins.

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#338]
I'm not sure this should happen or if it should be considered a breaking change.  This is by request of @bcoe at https://github.com/istanbuljs/nyc/issues/947#issuecomment-474464888

**Comment by bcoe** [comment]
@coreyfarrell what version of Node.js does BigInt land in? I'd argue we should enable it and just bump the major, as soon as most release lines have it; wouldn't it only break folks who have what would have been invalid syntax in code prior to this any ways?

**Comment by coreyfarrell** [comment]
It's in 10.15.3.  I don't know if it was part of 10.0.0 or if it was added later.  I think you're correct that it wouldn't break anything.  I'm actually leaning towards thinking this would not be a breaking change for istanbul-lib-instrument or nyc.  bigInt is stage 3 per https://github.com/tc39/proposal-bigint#state-of-the-proposal so that indicates the spec should be reasonably stable.

@loganfsmyth do you have any advice on this matter?  How does babel decide to transition a parser plugin to the core?  I assume that specifying `bigInt` parser plugin will never throw an invalid config error for babel 7, if it becomes core to the parser then specifying it will just become a noop?
