### ISSUE TITLE
istanbul-lib-hook: Investigate using `pirates` for hooking.

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#346]
`@babel/register` uses it, consider using it as well.

**Comment by SimenB** [comment]
I added it to Jest for transpiling `globalSetup` and `globalTeardown` as well. Worked a treat :)

**Comment by coreyfarrell** [comment]
I've looked into this and found an issue.
```js
require.extensions['.js'] = customHook;
```
append-transform incorporates `customHook` into the transformation chain, pirates does not.  nyc specifically tests for this so I'm no longer interested in pursuing this issue.

**Comment by SimenB** [comment]
could you provide some details? If it's an issue with pirates, maybe open an issue there? From the looks of it it shouldn't affect Jest's usage of it, but maybe `@babel/register`?

**Comment by coreyfarrell** [comment]
I've opened ariporad/pirates#57.  I don't know how jest adds the transpile hooks.  `@babel/register` is likely affected.  It's definitely an edge case but I have to lean on the side of not breaking it.

**Comment by SimenB** [comment]
Jest's implementation is here: https://github.com/facebook/jest/blob/8d0b5e2234d378920eb87112933c5c03016fb98e/packages/jest-transform/src/ScriptTransformer.ts#L467-L518

**Comment by coreyfarrell** [comment]
I think my view is that nyc has to mess with `require.extensions` to function and if the purpose of a module is to mess with `require.extensions` then I want nyc to allow them to do testing with coverage.  It's difficult to tell users "do as I say, ignore what I do".

**Comment by SimenB** [comment]
Yeah, seems reasonable 👍 Hopefully node provides proper hooks for this at some point (like https://github.com/nodejs/modules/issues/351)
