### ISSUE TITLE
test-exclude: Remove `**/node_modules/**` from the default exclude list.

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#347]
We should remove this from the default list, just let `excludeNodeModules: true` (the default) add it.  This will make it easier for projects to disable excludeNodeModules (they won't have to override the default excludes to actually remove `**/node_modules/**`).

I'm on the fence about this being a breaking change or not.

**Comment by JaKXz** [comment]
I'd even say it's a `fix`

**Comment by coreyfarrell** [comment]
PR is up.
