### ISSUE TITLE
migrate on `neo-async`

### ISSUE THREAD

**Issue by evilebottnawi** [istanbuljs/istanbuljs#353]
Repo: https://github.com/suguru03/neo-async
Why? It is faster. I can send a PR.

**Comment by coreyfarrell** [comment]
I appreciate the suggestion however our current plan is to deprecate / discontinue the `istanbul-api` module in favor of the individual modules.  I do not think we should make a change such as this when we intend to stop supporting the module in the near future.  All other modules with async functionality will use native async/await (we'll soon be requiring node.js 8).
