### ISSUE TITLE
nyc is not reporting test result to teamcity.

### ISSUE THREAD

**Issue by aniltomar10** [istanbuljs/istanbuljs#357]
I have time command in my package.json file.
"coverage": "nyc --reporter teamcity --reporter html --reporter text npm test",

Using "npm run coverage" in teamcity step. It's executing test cases and I also see the code coverage tab. But it doesn't report test results to team city.

**Comment by coreyfarrell** [comment]
@aniltomar10 have you been able to create a minimum reproduction repository as @JaKXz requested?  Also I'd suggest requested help/advice at a teamcity support/community forum, none of the istanbul maintainers know teamcity.

**Comment by coreyfarrell** [comment]
@aniltomar10 if you are able to provide the required information feel free to comment and we can reopen this issue, for now though I'm closing as we do not have the information required to assist you.
