### ISSUE TITLE
Create new module istanbul-lib-processinfo based on nyc:lib/process.js

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#358]
* [ ] Scope
* [ ] API definition
* [ ] Implementation
* [ ] Testing
* [ ] Documentation
* [ ] Release

**Comment by isaacs** [comment]
Some initial scope and API definition, docs, and a rough cut at implementation: https://github.com/istanbuljs/istanbul-lib-processinfo
