### ISSUE TITLE
Support for multiple text-summary coverage for different directories in a repo

### ISSUE THREAD

**Issue by sakhi-sl** [istanbuljs/istanbuljs#360]
Hi I am trying to generate `text-summary` coverage for different folders in a repo. But it shows global text-summary coverage. Like shown in below:

![image](https://user-images.githubusercontent.com/48210502/55725629-627e5800-5a0e-11e9-950b-dd476708df37.png)

Is there a way to show multiple text-summary for individual directories? I don't see any thing related to it in the documentation.

Thanks

**Comment by JaKXz** [comment]
The `text` reporter does this, as well as `lcov` / `html`.

**Comment by coreyfarrell** [comment]
Yes as @JaKXz has pointed out the `text` report will show you directories in the terminal.  I'm closing this issue as the text-summary report is showing what is intended which is a summary of global coverage.
