### ISSUE TITLE
Remove config loading from test-exclude?

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#392]
The purpose of this proposal is to simplify `test-exclude` and remove `read-pkg-up` and `require-main-filename` dependencies.  nyc doesn't (can't) use this functionality.

This was added a very long time ago in istanbuljs-archived-repos/test-exclude#1.  @bcoe do you remember if this was added for a specific request?  CC @JaKXz

**Comment by bcoe** [comment]
@coreyfarrell doesn't ring a bell, might have just been me being a bit of an architecture astronaut.

**Comment by JaKXz** [comment]
I think it predates the monorepo and was a feature for those who might have wanted to use it outside of Istanbul/nyc

**Comment by bcoe** [comment]
https://github.com/istanbuljs-archived-repos/test-exclude/pull/1

**Comment by coreyfarrell** [comment]
Ultimately my question is can we remove it (obviously in semver-major).  In addition to simplifying the code / reducing the dependencies I think libraries should not load configuration (unless that's the specific purpose of the library).  Loading configuration is the job of applications.

**Comment by bcoe** [comment]
@coreyfarrell as long as c8 and nyc aren't using it, and it's a major, I'd vote retire it in a major.

**Comment by coreyfarrell** [comment]
Apparently this functionality is used as a last resort by babel-plugin-istanbul but I'm not going to revert the change to test-exclude.  test-exclude only supported loading from `package.json`.  My plan is to create a small module which will contain nyc's config loading function, then migrate nyc and babel-plugin-istanbul to use it.  This way the babel plugin will actually support loading from all potential nyc configuration sources (`.nycrc`, `.nycrc.yml`, `.nycrc.json`, `nyc.config.js`, and of course `package.json`).  I suspect this will move `package.json` loading out of yargs for nyc itself but that will be a good thing.  This will allow us to control priorities like what happens if `package.json` contains an `nyc` key but `.nycrc.json` also exists.

I'm not sure if we want to use `cosmicconfig` for this or keep our own solution.  I haven't been able to fully evaluate `cosmicconfig` for this purpose yet.

**Comment by bcoe** [comment]
@coreyfarrell works for me :+1: unfortunately, as none of us seem to really use a babel stack, we seem to often drop it on the floor -- would be good to find a champion for that library.

**Comment by coreyfarrell** [comment]
@bcoe I wouldn't call myself a champion for that library but I am a user.  In theory removal of the config loading ability would have changes results for me in the past, but since I'm generally not putting my nyc config into `package.json` anymore I would have run into this issue anyways.  Also nyc still processes the include/exclude when producing reports so that will mask the issue but wasting CPU/memory by generating coverage for files that will be tossed during reporting.

**Comment by coreyfarrell** [comment]
I've created https://github.com/coreyfarrell/load-nyc-config.  The intent is to publish this as `@istanbuljs/load-nyc-config`, then make nyc use this for configuration loading.  I pushed under my own username so we can decide if this is a proper module name before I push to istanbuljs.

CC @bcoe @JaKXz

**Comment by JaKXz** [comment]
I think that looks great! But, if we're going to have a custom library, it should definitely have validations for NYC's config options

**Comment by coreyfarrell** [comment]
This will introduce two breaking changes to handling of the nyc flag `--nycrc-path`.
* `nyc --nycrc-path something.json` will cause nyc to exit with failure if `something.json` cannot be found in cwd or above.
* This flag will make it so only the specified file(s) are searched for.  Currently with `nyc --nycrc-path=my-nyc-config.json` we still search for `.nycrc.{json,yml,yaml}` and `nyc.config.js`.  This change will ensure that if `.nycrc.json` is in the current path still look in `..` for `my-nyc-config.json`.

Minor change, `nyc --help` will no longer be able to show a `default` value for `--nycrc-path`.  This is because we need the value to be undefined by default.

**Comment by coreyfarrell** [comment]
@JaKXz I agree that we should have validation, please keep in mind though the initial goal is to move the logic from nyc to a module where it can also be used by babel-plugin-istanbul.

I'm not entirely sure what validation would look like at this stage.  I assume we would enforce specific types on all known fields.  Do we block unknown fields?  Is it possible to avoid duplication between nyc command-line stuff and this validation?  Does the loadNycConfig function perform validation or do we have a separate function?  I think a separate function would be needed so nyc can validate the result of yargs including command-line args?

**Comment by coreyfarrell** [comment]
@bcoe @JaKXz any objection if I create `github.com/istanbuljs/load-nyc-config` and push the contents as-is?  I won't publish to npm yet so we can further discuss, the question at this point is about the module being named `@istanbuljs/load-nyc-config` instead of `istanbul-lib-load-nyc-config`.

**Comment by JaKXz** [comment]
@coreyfarrell my only question is should it be part of the nyc repo and we just make it a mono-repo? 

Also re: validations, I haven't had much time to think closely about it, but ideally we do everything you mentioned and validate the config files, and the command line input if yargs isn't already... maybe yargs should take a validator function? 🤷‍♂

**Comment by coreyfarrell** [comment]
My preference is a stand-alone repo.  It doesn't depend on any other istanbul libraries and the tests have 100% coverage.  TBH I'm still trying to get used to dealing with the monorepo, it has definite pros and cons.  I see the value when it comes to `npm test` for the inter-dependent modules (coverage, instrument, source-maps, reporting).  I find it to be limiting when creating releases (and sometimes even burdensome).  If lerna had the ability to release individual packages that would address a significant hesitation with monorepos.  Also as far as I can tell you can't override the default version bump with a monorepo where you can do that for individual packages (`standard-release -r minor`).  Unfortunately I'm not sure it's even reasonable for lerna to support these things.

So my preference is that we decide if something goes in monorepo based on "does this module benefit from being tested with `master` of everything else".  My default position is against monorepo unless it is of a benefit.  I've considered proposing we move nyc itself into this monorepo (istanbuljs/istanbuljs), but honestly I've held off proposing this because of the monorepo process for creating releases.

**Comment by JaKXz** [comment]
> please keep in mind though the initial goal is to move the logic from nyc to a module where it can also be used by babel-plugin-istanbul

I'm sorry I missed this in your comments! Let's move this conversation to slack.

**Comment by coreyfarrell** [comment]
I've created https://github.com/istanbuljs/load-nyc-config.  @JaKXz one thought I just had, should this module used named exports instead of the default?  I mean right now all it has is the one function to load from config files, but assuming in the future we will have a separate validation function maybe we should just use named exports from the start.

**Comment by bcoe** [comment]
@coreyfarrell if your gut is telling you named exports, might just go that route, it really doesn't add too much cruft these days now that you can simply:

`const {configLoader} = require('load-nyc-config')`

Work is looking good :+1:

**Comment by coreyfarrell** [comment]
I think https://github.com/istanbuljs/load-nyc-config is in a state where it can be published to npm and used by nyc / babel-plugin-istanbul (obviously once they drop node.js 6).  Using named export means that we can add validation as a non-breaking change once the functionality of it is fully spec'ed.

I'm closing this bug, if you find any issues with the new module please post a bug or PR to it.
