### ISSUE TITLE
Move nyc into monorepo?  Move some auxiliary packages out?

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/istanbuljs#407]
I have (very) mixed feelings on this but I think it's worth opening a discussion.  Moving nyc into the monorepo could make it easier to deal with breaking changes.  Specifically some of the packages already in the monorepo are very complex and nyc is closely dependent on them.  This same argument could apply to babel-plugin-istanbul as well.

On the flip side I think some of the modules currently in the monorepo could/should be in stand-alone repos.  Specifically config presets and `test-exclude`.  See second paragraph of https://github.com/istanbuljs/istanbuljs/issues/392#issuecomment-494473732 for my view on what belongs in monorepo or not.

**Comment by bcoe** [comment]
@coreyfarrell I'd honestly like to keep `nyc` out of a mono-repo; I've liked using mono-repos for sets of utility libraries, but for important marquee libraries like `nyc`, `yargs`, etc., I prefer the flexibility that comes with them being in their own repo ... I'm a pretty strong no on mono-repo.

**Comment by bcoe** [comment]
It's not just about interdependencies, it's about:

* search engine optimization: I want folks to find the main nyc GitHub repo when they google.
* documentation: I want documentation to be in the top-level GitHub repo, I want it to be easy to extend on this documentation further with a `docs` folder.

**Comment by coreyfarrell** [comment]
I can see having the nyc readme in the top-level of the repo as valuable so consider the 'move nyc' side of this discussion closed.  Same argument applies to babel-plugin-istanbul, this is an 'end-user' module vs istanbul-lib-instrument which is a low-level API generally meant for use by frameworks only.

What is your opinion on moving `test-exclude` and the nyc config presets out of the monorepo?

**Comment by shinnn** [comment]
Though I'm not a maintainer of this project, I have a concern for `nyc` migration to this repository from the perspective on development efficiency.

This repository already spends about 7 minutes for every CI build. https://travis-ci.org/istanbuljs/istanbuljs/builds/537569146 If you add the large `nyc` project to this repository, duration of the test would become more critical, especially for pull request reviews where a contributor submits a patch, a reviewer requests a change, the former tweaks the patch, the latter requests another change and so on.

**Comment by bcoe** [comment]
@coreyfarrell you summarized my feeling very well, mono-repos seem pretty great for _insider baseball_ low-level libraries ... When I put test-exclude in the mono-repo, I felt it fit this bill (I didn't expect it to gain _too_ much popularity as a tool outside of the ecosystem of modules we work on).

What are your thoughts? I could have my arm twisted into moving those libraries out of the mono-repo.

**Comment by coreyfarrell** [comment]
I've found another potential reason to move `test-exclude` and `@istanbuljs/nyc-config-*` out of this repo.  They use the `ISC` license where everything else uses BSD-3-Clause.  This means we cannot accurately add a LICENSE file to the root of the repository, so Github does not report a license.  Granted we could **probably** change the `@istanbuljs/nyc-config-*` modules to use BSD-3-Clause (very few contributors to those modules).  `test-exclude` has had many contributors I don't think it's practical to try changing the license.

@bcoe @JaKXz Please let me know if you have objections to moving these ISC licensed modules out of the monorepo or if I can go ahead.  I'd like to move on this ASAP.

**Comment by coreyfarrell** [comment]
Little note, apparently https://github.com/istanbuljs/test-exclude previously existed, was moved to https://github.com/istanbuljs-archived-repos/test-exclude when the monorepo was created.  Probably need to move the repo back / set proper permissions then I can push an 'import from monorepo' commit.

**Comment by bcoe** [comment]
@coreyfarrell this is done, you're also now the owner of the organization; use your powers wisely.

**Comment by coreyfarrell** [comment]
I think the `test-exclude` is probably good enough.
