### ISSUE TITLE
test-exclude doesn't work with files in different drives on Windows

### ISSUE THREAD

**Issue by eight04** [istanbuljs/istanbuljs#418]
```js
exclude = require("test-exclude");
exclude({cwd: "C:\\"}).shouldInstrument("D:\\some-file"); // true
```
This line doesn't work on Windows:
https://github.com/istanbuljs/istanbuljs/blob/c4e8b8e640acba43ecbe26ca3032a951de3ac3a6/packages/test-exclude/index.js#L96

Should we switch to something like [is-path-inside](https://github.com/sindresorhus/is-path-inside)?

**Comment by coreyfarrell** [comment]
Instead of bringing in additional dependencies maybe we could just replace the regex with:
```js
if (!minimatch(path.resolve(this.cwd, filename), path.join(this.cwd, '**'), {dot: true})) {
```

@JaKXz @bcoe any feelings on this?  minimatch is probably less efficient than using `is-path-inside` but I would expect that minimatch should be reasonably efficient for a `startsWith` type of match.

**Comment by bcoe** [comment]
@coreyfarrell @eight04 I'd be tempted to just pull this bit into a helper, like `outside-project-root.js`, and then just use a line like:

`const isWindows = process.platform === "win32`

To determine OS and fork logic a bit, I think we can probably pull something together that's not too painful right, if we know it's a Windows OS? at the cost of a branch in logic.
