### ISSUE TITLE
Cobertura Coverage: condition-coverage per line does not work

### ISSUE THREAD

**Issue by mintel-ssallay** [istanbuljs/istanbuljs#42]
Related to #14.

Cobertura condition-coverage for branches is not recorded correctly. There is an issue (istanbuljs/nyc#530) with detailed information on observed/expected behavior as well as the quick fix I am currently using at work.

The fix is easy enough to do, but it breaks the "base coverage returns branch coverage by line" test for the istanbul-lib-coverage package. My initial solution:
```javascript
var line = branchMap[k].line || branchMap[k].loc.start.line
```

[Other](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/source-coverage.js#L3) [packages](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/lib/lcovonly/index.js#L53) in this repo prefer the "fixed" shape, so it seems that this fix should be safe to do without breaking anything else.

**Comment by bcoe** [comment]
@mintel-ssallay I'd love to work with you to fix the Covertura reporting; perhaps you could start by creating a failing test and and opening a pull request? Ideally I'd like to figure out a way to fix the Cobertura output, without breaking any tests -- perhaps we can make a tweak in the reporter itself?

**Comment by mintel-ssallay** [comment]
@bcoe, I have added the failing test. The fix I mentioned above would fix this new test without breaking the old one.

I found that the Clover reporter is also using this branchMap structure and is _also_ missing conditional line coverage, so I'm not sure if tweaking the Cobertura reporter directly would be the best solution.

**Comment by bcoe** [comment]
@mintel-ssallay this should now be fixed in the latest release of istanbuljs and nyc (nyc@10.3.0).

**Comment by mintel-ssallay** [comment]
The new version of nyc works as expected. Thanks for your assistance. I'll close out this issue now.
