### ISSUE TITLE
html-spa reporter bug when 2 directories are subsets of each other

### ISSUE THREAD

**Issue by lukeapage** [istanbuljs/istanbuljs#426]
```
/ab/file
/abc/file
```

If you click on "ab" you see
```
+ c
```
under the 'ab' folder rather than excluding it.

I can take a look at this bug.

**Comment by coreyfarrell** [comment]
Thanks for investigating.  Just to set expectations it's probably going to be in an `alpha` state for 3 weeks minimum.  I won't have much time to work on nyc during the next few days, none of the modules from this repository will reach final release state until nyc is ready to have a final release.
