### ISSUE TITLE
Bump handlebars version in istanbul-reports and release new version of handlebar api

### ISSUE THREAD

**Issue by dscalzi** [istanbuljs/istanbuljs#435]
There is a vulnerability in handlebars (see https://www.npmjs.com/advisories/755). It looks like you increased the version number, but the latest release of the istanbul-api is pointing to an older version of istanbul-reports.

Could you ensure everything is up to date and cut a new release of the 2.x line? Thanks.

**Comment by coreyfarrell** [comment]
istanbul-api and istanbul-reports both use semver range to install handlebars.  You just need to run `npm update` to pull the latest version.
