### ISSUE TITLE
Lodash prototype pollution vulnerability

### ISSUE THREAD

**Issue by notaphplover** [istanbuljs/istanbuljs#445]
It seems the last version of [istanbul-lib-instrument](https://www.npmjs.com/package/istanbul-lib-instrument) (3.3.0) requires the following packages:

- "@babel/generator": "^7.4.4".
- "@babel/traverse": "^7.4.5".
- "@babel/types": "^7.4.4".

Unfortunately, these packages have a dependency of lodash "^4.17.11". Lodash version 4.17.11 has a prototype pollution vulnerability (as described in the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v41712)) fixed at version 4.17.12.

Sooner or later, there will be a new version of this packages that will fix this vulnerability since [this PR](https://github.com/babel/babel/pull/10191/files) is merged.

I'm just creating the issue to notify this fact and request a dependency update once Babel's packages are updated.

**Comment by bcoe** [comment]
@coreyfarrell we should probably prioritize this. @notaphplover thanks for the report.

**Comment by coreyfarrell** [comment]
`lodash` is installed by a semver range.  This means that 4.17.12+ will automatically be installed unless you have a package-lock.json or yarn.lock which prevents automatic updates.  You can fix your repository by running `npm --depth 9999 update` (sorry I don't know the yarn command to do the same).

**Comment by coreyfarrell** [comment]
I'm closing this issue as the latest version of all modules require a version of babel which depends on `^4.17.13`.
