### ISSUE TITLE
No matching version found for @lerna/create@3.16.0

### ISSUE THREAD

**Issue by zhipu77** [istanbuljs/istanbuljs#448]
Cannot found @lerna/create@3.16.0 dependence version
![image](https://user-images.githubusercontent.com/19151740/61506306-36fb0880-aa14-11e9-8d3f-6868ef509996.png)

Only 3.15.0 found
![image](https://user-images.githubusercontent.com/19151740/61506350-5e51d580-aa14-11e9-950e-e4609feb6ba3.png)

OS:mac 10.14.5
Node Version: v8.9.3

**Comment by coreyfarrell** [comment]
This is likely an issue with the npm repositories, probably the mirror which is local to you has some outdated information.  This happens from time to time.  I suggest trying again after a delay, your local mirror will soon catch up.
