### ISSUE TITLE
How to Ignore all class or function calls in coverage

### ISSUE THREAD

**Issue by distante** [istanbuljs/istanbuljs#463]
In my angular project I use an instance of a [logger][1] that can be:

`this.logger.log()` `this.logger.warn()` or `this.logger.error()`

I want to be able to say to jest/istanbul coverage **"please ignore all the logger calls"** without the need to write manually `/* istanbul ignore next */` in all my files and logger calls.

Is it possible? I wasn't able to find anything related.

  [1]: https://www.npmjs.com/package/@saninn/logger

**Comment by coreyfarrell** [comment]
This is not possible nor is any feature like this planned.  The instrumenter does not perform this level of interpretation of the code needed to accomplish what I think you are asking for.  You can ignore a function itself:
```js
/* istanbul ignore next */
function doSomething(message) {
  return message || 'this return statement will not be reported as covered or uncovered';
}

doSomething('this call to doSomething will be reported as covered');
```

**Comment by distante** [comment]
> You can ignore a function itself:

You mean in the library it self?

**Comment by coreyfarrell** [comment]
The only way to ignore a the line of code highlighted in your image capture is to put an `istanbul ignore next` hint before it, or use `istanbul ignore else` before the branch.  Below is what I would recommend:
```js
/* istanbul ignore else */
if (normallyTrue) {
  // do normal stuff
} else {
  this.logger.error('abnormal thing happened');
}
```

**Comment by distante** [comment]
Ok, I wanted to prevent each call to the logger to be as "not covered" in general but looks like there is no other way.

Thanks!
