### ISSUE TITLE
Q: how to manually add coverage during a nyc instrumented test-run

### ISSUE THREAD

**Issue by jpommerening** [istanbuljs/istanbuljs#49]
Hi,

I've got a fun little setup.

I'm running `mocha` instrumented with `nyc`, like `nyc -n src -i babel-core/register mocha`. In itself, this part works.
Most of the tests are unit-tests running directly in the nodejs instance. Other tests are end-to-end tests which start a webdriver-controlled browser, bundle sourcefiles with webpack using babel and `istanbul-instrumenter-loader`, then do some browser tests and send `window.__coverage__` back to the test-runner via the webdriver connection. The test runner then writes out the source-mapped coverage data to `.nyc_output` (with a little help from `istanbul-api`) where it gets picked up by nyc and reported. This works too.

However, if I run both the normal testsuite and the end-to-end tests in the same mocha run, the manually written coverage overrides coverage data from nyc. That is, if I have 100% coverage on `src/thing.js` in the regular tests, but only 70% in the end-to-end tests, nyc reports only 70%.

Is there something I can do to somehow funnel the browser's coverage data into the running nyc instance?

**Comment by jpommerening** [comment]
After a while I figured I could just mutate the global `__coverage__` object. At that point, merging the source-mapped data into it was straightforward. Sometimes you just have to write things down (into an issue) to figure out how to solve the problem :)

Thanks anyway!

**Comment by bcoe** [comment]
@jpommerening I'm glad you figured out an approach 👍 please let me know if there's anywhere we could document this better.
