### ISSUE TITLE
Convert 'SF' in the 'lcov.info' file to a relative path

### ISSUE THREAD

**Issue by guibwl** [istanbuljs/istanbuljs#491]
I need to generate 'lcov.info' local before upload it to the server for 'sornaQube',
But 'SF' in 'lcov.info' is absolute path, which is not match the server files path;

### Example :

* 'lcov.info'  file is generated on my computer: 

```info
TN:
SF:/Users/myUsersName/path/__test__/testFile.js
FN:19,uninstallScripts
FN:22,(anonymous_1)
FN:26,(anonymous_2)
...
```

* Test file path on the server should be:
```
SF:/root/server/path/__test__/testFile.js
```

Is there anywhere can configure the 'SF' ?
Thanks!

**Comment by coreyfarrell** [comment]
https://github.com/istanbuljs/istanbuljs/pull/492 implemented relative paths for lcov reports, by default `process.cwd()` or the project directory for projects that use nyc.  This feature is released to istanbul-reports 3.0.0 and nyc 15.0.0.
