### ISSUE TITLE
No values for html report

### ISSUE THREAD

**Issue by JacekIonoview** [istanbuljs/istanbuljs#520]
Hello, In my angular app I'm using itambul for generate my code coverage report. The issue is that currently, it generates html files without any values. I've updated all required packages:

package.json devDependencies:
```
"devDependencies": {
    "@angular-devkit/build-angular": "~0.13.4",
    "@angular/cli": "~7.3.4",
    "@angular/compiler-cli": "~7.2.7",
    "@angular/language-service": "~7.2.7",
    "@types/googlemaps": "~3.30.17",
    "@types/jasmine": "~2.5.54",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~11.10.4 ",
    "codelyzer": "^5.1.0",
    "husky": "^2.4.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "karma-mocha-reporter": "^2.2.5",
    "ng-mocks": "^8.1.0",
    "ngx-spec": "^2.1.4",
    "protractor": "~5.4.2",
    "sass-lint": "^1.13.1",
    "ts-node": "~8.0.2",
    "tslint": "^5.17.0",
    "typescript": "~3.2.4"
  }
```
karma.conf.js:
```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: [
      'jasmine',
      '@angular-devkit/build-angular',
    ],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma'),
      require('karma-mocha-reporter'),
    ],
    client:{
      clearContext: false,
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, 'coverage'),
      reports: [
        'lcovonly',
        'text-summary',
        'text',
        'html',
      ],
      fixWebpackSourcePaths: true,
    },
    files: [
      'src/app/spec/mocks/js/google-mock.js',
      {
        pattern: 'src/assets/**',
        watched: false,
        included: false,
        nocache: false,
        served: true,
      },
    ],
    proxies: {
      '/spa/assets/': '/base/src/assets/',
    },
    reporters: [
      'mocha',
      'progress',
      'kjhtml',
    ],
    customLaunchers: {
      ChromeHeadlessNoSandbox: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox'],
      }
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    mochaReporter: {
      ignoreSkipped: true,
      colors: {
        success: 'green',
        info: 'blue',
        warning: 'yellow / orange',
        error: 'red',
      },
      symbols: {
        success: '+',
        info: '#',
        warning: '!',
        error: 'x'
      },
    },
  });
};
```
**text-summary** and **text** reports are working properly,  example output of `ng test --code-coverage` is:
![Screenshot from 2020-01-23 13-44-25](https://user-images.githubusercontent.com/48915271/72985578-8ddc0300-3de6-11ea-9cb9-15b1a4cedce5.png)

As you can see **text-summary** and **text** were generated with values. Html files were also generated:
![Screenshot from 2020-01-23 13-47-13](https://user-images.githubusercontent.com/48915271/72985754-ed3a1300-3de6-11ea-9b6d-a81d2734c4b4.png)

But here is a preview of index.html from coverage directory in the browser without any values:
![Screenshot from 2020-01-23 13-49-07](https://user-images.githubusercontent.com/48915271/72985852-32f6db80-3de7-11ea-9df4-1ee8ef72fd92.png)

Any ideas?

**Comment by coreyfarrell** [comment]
This is due to a breaking change in handlebars which was released semver-minor.  This is fixed in istanbul-reports 2.2.7 and 3.0.0.

Please ensure you are not using older versions of istanbul-reports.  Maybe delete your node_modules and package-lock.json then reinstall.  If something is forcing you to use an older version of istanbul-reports your only option is to install `handlebars@=4.5.3` on your own project. That should pin to the last version of handlebars before the breaking change.

**Comment by AnyhowStep** [comment]
I had this problem, too, and was confused as heck.
Thank you for the fix!

**Comment by AnyhowStep** [comment]
I had this problem, too, and was confused as heck.
