### ISSUE TITLE
Can reporters generate html page?

### ISSUE THREAD

**Issue by shenlvmeng** [istanbuljs/istanbuljs#530]
Hi, are there any ways to generate an html page, but not static html files, by istanbul-reports on server?  If not, are there any future plans? We met a scenario recently where the project's coverage report needs to be visible through the browser.  It seems like the html reporter can only output files.

Thanks.

**Comment by coreyfarrell** [comment]
You can run the `html` or `htmlspa` report and then use any HTTPD server of your choice to publish the output folder.  istanbul-reports is not an HTTPD server and there is no plans to implement such a feature.

Note you can have your browser open the report directly from the filesystem, for example I often run `firefox coverage/index.html` to view the reports.
