### ISSUE TITLE
Cobertura coverage version not supported by SonarQube

### ISSUE THREAD

**Issue by yejcob** [istanbuljs/istanbuljs#537]
Why is the version of cobertura coverage report set to 0.1 this version is not supported for sonarqube can it be updated?

> ERROR: Caused by: Unknown report version: 0.1. This parser only handles version 1.
> ERROR: 
> The SonarQube Scanner did not complete successfully

**Comment by fergardi** [comment]
How did you fix this issue? I'm experiencing the same.
