### ISSUE TITLE
TypeScript decorators make instrumentation fail

### ISSUE THREAD

**Issue by codefoster** [istanbuljs/istanbuljs#539]
I believe this is similar but distinct from [issue 535](https://github.com/istanbuljs/istanbuljs/issues/535).

I'm trying to instrument the `.ts` files in my project (instead of the `.js` files in the `dist` folder). I'm not certain that's the advised approach, but that's what I'm trying to do. When I add a decorator to a class in my source code, that file is no longer instrumented. I found in the `packages/istanbul-lib-instrument/test/plugins.test.js` file that decorators are intended to fail. It appears that can be overwritten for bable, but I'm not sure if that's the case for TypeScript as well.

**Comment by coreyfarrell** [comment]
Please link to a project or a repository demonstrating how you are trying to instrument your code.  You may need to enable the `typescript` babel plugin for typescript decorators to work, how to do this depends on how you are instrumenting.

**Comment by codefoster** [comment]
Take a look at the [codefoster/controller-tests branch of retaildevcrews/helium-typescript](https://github.com/retaildevcrews/helium-typescript/tree/codefoster/controller-tests). You can see my `.nycrc.json` file at the root. An example of some files that are not getting instrumented are in `src/services`.

**Comment by codefoster** [comment]
Hold the phone. I tweaked my `.nycrc.json` again and it worked. I'm seeing all `.ts` files now - even those with decorators. Sorry.

**Comment by svkr2k** [comment]
Hi @codefoster , @coreyfarrell ,
Please let me know how you solved the issue with instrumenting classes with decorators in typescript.
Awaiting the solution from you.
Regards,
Rajesh Seenivasan
