### ISSUE TITLE
missing istanbul-reports/lib/html/assets directory after install

### ISSUE THREAD

**Issue by erwin16** [istanbuljs/istanbuljs#54]
I installed istanbul 0.4.5 but upon running I get an error with the html reporter

Error: ENOENT: no such file or directory, scandir '../node_modules/nyc/node_modules/istanbul-reports/lib/html/assets'
    at Object.fs.readdirSync (fs.js:871:18)

checking my node_modules directory , effectively te assets directory is NOT installed ..

**Comment by erwin16** [comment]
updating by hand , adding dies and file into  Istanbul-reports/lib/html/assets .. it runs now..
why this directory is missing upon installation ?

**Comment by bcoe** [comment]
@erwin16 what version of the npm client were you using out of curiosity?

**Comment by bcoe** [comment]
@erwin16 just checking in, curious what version of npm or yarn you're using to install -- this sounds like an issue with the installer.

**Comment by cyco** [comment]
This seems to be a bug / feature in yarn relating to the `yarn clean` command. As suggested in https://github.com/yarnpkg/yarn/issues/832 removing `.yarnclean` from your project root fixes the problem.

**Comment by bcoe** [comment]
This should be fixed now in newer versions of yarn.
