### ISSUE TITLE
Dependency update to fix vulnerability

### ISSUE THREAD

**Issue by LucaFranceschini** [istanbuljs/istanbuljs#548]
`istanbul-lib-instrument` depends on `@babel/core` (with `^7.7.5`). Version 7.9.0 of Babel fixed a problem with a vulnerability on a (recursive) dependency. Should the dependency version range be updated to `^7.9.0`?

**Comment by coreyfarrell** [comment]
We do not publish updates to force this sort of update.  Non-vulnerable versions are accepted per the existing semver range.  You can run `npm update --depth=9999` to fix the issue or delete your lockfile / node_modules and install fresh.
