### ISSUE TITLE
istanbul-lib-source-maps typings for transformCoverage function are incorrect

### ISSUE THREAD

**Issue by Charles-Gagnon** [istanbuljs/istanbuljs#554]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/istanbul-lib-source-maps/index.d.ts#L36 says that it returns a `CoverageMap`, but the actual function was converted to async and now returns `Promise<CoverageMap>` https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-source-maps/lib/map-store.js#L172

**Comment by coreyfarrell** [comment]
Please open a bug with DefinitelyTyped, the issue is that those typings are for the previous version of istanbul libraries.

**Comment by Charles-Gagnon** [comment]
Alright, but the typings say they're for version 4.0.0 of the library https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/istanbul-lib-source-maps/index.d.ts#L1 - which is the current released version. 

Do you not maintain the typings files yourself?

**Comment by Charles-Gagnon** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43740

**Comment by coreyfarrell** [comment]
I do not maintain typings (my knowledge of TypeScript is extremely basic).  Sorry this is not something I have the capability to help with.
