### ISSUE TITLE
Feature request: add parsing hints for ignoring a try/catch block.

### ISSUE THREAD

**Issue by Anadian** [istanbuljs/istanbuljs#559]
Specifically, a common pattern in my code is something like this:
```js
try{
  ExternalModule.SomeFunctionWhichMayOneDayThrowAnError()
} catch(error){
  console.log(error);
}
```
There currently isn't a way to trigger the error but I still want to have the `catch` block there as a fail-safe should some hypothetical error ever be thrown from `SomeFunctionWhichMayOneDayThrowAnError()`; the problem with this is, obviously, if an error is never thrown, `catch` block won't be covered. So I'd like to use a parsing hint to tell istanbul/nyc to not worry about the `catch` block: my first thought on how to do this would be to add an `/* istanbul ignore catch */` comment before the `try` statement, similar to how `/* istanbul ignore else */` works, however `ignore catch` doesn't appear to be recognised as a parsing hint so the `catch` still shows as uncovered in the coverage report and putting a `/* istanbul ignore next */` before the statement results in both the `try` and `catch` blocks be ignored.

So yeah, I think there should be a way to specify a parsing hint to ignore a specific try/catch//finally block similar to how you can single out an `if` or `else` block.

**Comment by coreyfarrell** [comment]
This is possible already.
```js
try /* istanbul ignore next */ {
  console.log('coverage suppressed due to ignore next between `try` and `{`.');
} catch(error) /* istanbul ignore next */ {
  console.log('coverage suppressed due to ignore next between `catch(error)` and `{`.');
} finally /* istanbul ignore next */ {
  console.log('coverage suppressed due to ignore next between `finally` and `{`.');
}
```

Note in the above example it doesn't make much sense to ignore the `try` or `finally` blocks since they (should) always run.  If you need to ignore the whole thing you can do:
```js
/* istanbul ignore next */
try {
  console.log('no coverage');
} catch(error) {
  console.log('no coverage');
} finally {
  console.log('no coverage');
}
```

I'm going to close this out as the requested functionality is already supported.  In this case we need to avoid added complexity which would come from adding a new coverage hint.  So we can only consider new hints for cases which cannot be served by the existing hints.
