### ISSUE TITLE
Instrumenting to track performance/memory

### ISSUE THREAD

**Issue by brettz9** [istanbuljs/istanbuljs#565]
Has any thought been given to utilizing istanbul (`istanbul-lib-instrument`?) to instrument code such that not only line visits can be tracked but also performance times per line would be checked (whether to be used later for time median/averages or totals of time taken per line)?

While this might seem out of scope for a project focused on coverage, given that it would also require instrumenting per line, and could also be useful to similarly hook into one's testing pipelines, I thought I would see.

Particularly interesting for possible implementation might be the Performance API, available both in [browsers](https://developer.mozilla.org/en-US/docs/Web/API/Performance) and in [Node](https://nodejs.org/api/perf_hooks.html).

While the same API does not appear to be supported in Node, this API also has a [memory API](https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory), making it possible that one could also get median, average, or total memory usage changes per line as well.

**Comment by coreyfarrell** [comment]
Thank you for requesting unfortunately this is mostly out of scope for istanbuljs.  I think it would be reasonable to have some sort of hit based heat-map report.  I'm thinking something which could identify the hottest paths of your code, so it could say "a statement at line 52 of file.js was run 564,134 times".  This could be accomplished with the existing coverage data it would be a matter of writing a report which sorts the data by number of hits and reports on the the lines with the highest hit-count.

As for Performance API I suspect this would have significant overhead if applied everywhere, so you would change your measurements by measuring.  You would instead want to hit counts to identify places where performance measuring would be useful - don't measure the performance of the function you call once, measure performance of the functions you call 100,000 times.  In particular I would expect you'd need to avoid recursive runtime recording.

**Comment by brettz9** [comment]
Re: the visit count heat map, yes, I am actually working on such a tool right now which got me thinking outward a little bit to other ways of determining potentially bottlenecks (though my tool is currently being implemented as a reporter which gets a list of files and lines out of the coverage data (thus my interest in https://github.com/istanbuljs/nyc/issues/1311 -- documentation for the reporter methods would be helpful too, though I know there is always source!), sorting optionally by file or by visits, so one can see the top most visited items by file or by project.

As far as Performance API, as it would occur for every line, I would think this would be keeping the variables constant, no? I know one can manually take advantage of the API as it is now, but just seems like it'd be useful--even if slow--to get an out-of-the-box map of line duration. Not something probably to run frequently, but just as a tool to give a quick audit for say a new project. Re: counting the functions you call 100,000 times, yes, that points to value in the total time account, but average/median duration per line could also hold some value.

Anyways, thanks for your thoughts!

**Comment by brettz9** [comment]
Re: the visit count heat map, yes, I am actually working on such a tool right now which got me thinking outward a little bit to other ways of determining potentially bottlenecks (though my tool is currently being implemented as a reporter which gets a list of files and lines out of the coverage data (thus my interest in https://github.com/istanbuljs/nyc/issues/1311 -- documentation for the reporter methods would be helpful too, though I know there is always source!), sorting optionally by file or by visits, so one can see the top most visited items by file or by project.

As far as Performance API, as it would occur for every line, I would think this would be keeping the variables constant, no? I know one can manually take advantage of the API as it is now, but just seems like it'd be useful--even if slow--to get an out-of-the-box map of line duration. Not something probably to run frequently, but just as a tool to give a quick audit for say a new project. Re: counting the functions you call 100,000 times, yes, that points to value in the total time account, but average/median duration per line could also hold some value.

Just seemed like all the work you have put into adding the ability to instrument and build reports could be handy for this proposed project. I don't know if it would add too much to your own performance to abstract out the responsible portions of the code to allow reuse.

Anyways, thanks for your thoughts!
