### ISSUE TITLE
replace classes with static-functions in `/packages/istanbul-lib-report` and `/packages/istanbul-reports`

### ISSUE THREAD

**Issue by kaizhu256** [istanbuljs/istanbuljs#568]
apologize beforehand for this political PSA.

i'm maintainer for zero-dependency, browser-based npm-package istanbul-lite.  recently, finished rewriting original istanbul v0.2.16 text-reporter and html-reporter as stateless, static-functions that take in coverage-tree and spit out respective text-report and html-report files with zero class-instantiations.

the source-code for static-functions `coverageReportCreate(__coverage__)`, `reportTextWrite(node)` and `reportHtmlWrite(node)` is [here](https://github.com/kaizhu256/node-istanbul-lite/blob/3298cfe358a3f30116eb6ccc0ed047fcc9c1e723/lib.istanbul.js#L10508) (~1200 loc including comments).

and here is what the html-report output looks like:
https://kaizhu256.github.io/node-istanbul-lite/build..alpha..travis-ci.org/coverage.html/node-istanbul-lite/lib.istanbul.js.html

i plan to next convert the instrumenter from class-object to stateless static-function as well (take in source-code and output instrumented-code with zero-config).

maybe this could serve as inspiration for istanbuljs to remove its classes as well ... probably not, but wanted to let you know its doable.

feel free to close this issue anytime.

**Comment by coreyfarrell** [comment]
Be aware the current instrumenter (istanbul-lib-instrument) is built upon babel, so completely classless is not possible.  In addition changing our API structure would cause a ripple of problems to third parties (jest, custom reports, karma plugins).

Our use dependencies such as babel is a great benefit - istanbuljs does not have responsibility for creating/testing/maintaining a parser or code generator (nor do we have the resources to take this on).  Leaving these details to babel helps us to support modern JavaScript.  The modules we use are carefully selected and are generally well tested.

I wish you luck but this is not a direction we can take.  Please be warned https://github.com/gotwarlost/istanbul has not been maintained in years, istanbuljs has diverged from it significantly.

**Comment by kaizhu256** [comment]
i know its wishful thinking ; )

- fyi, the old istanbul-reporter is still relevant and viable for modern es, because the istanbul `__coverage__` object's structure has not changed since.

- and the old istanbul-instrumenter also still relevant and viable, after i upgraded dependencies `acorn`, `extraverse.js`, `estools/lib/code.js`, and `escodegen.js` to latest versions.
