### ISSUE TITLE
All the values are missing in (otherwise OK) HTML report

### ISSUE THREAD

**Issue by xMort** [istanbuljs/istanbuljs#577]
We started to post links to HTML coverage report (linked to Jenkins artifact) to our pull requests recently and I noticed that from time to time the HTML report is missing all the values. It contains records for all the files, it can be drill into packages and all the rows have colors based on coverage (red, green, yellow) that match the previous reports but the values are not there. I don't see any errors in the output.

We use jest@24.8.0 with istanbul-lib-coverage@2.0.3, istanbul-reports@2.1.1 and istanbul-lib-report@2.0.4 (these are jest dependencies that I found resolved in lock file).

Is this some known error in previous versions?

![image](https://user-images.githubusercontent.com/1880148/90236364-f215f100-de22-11ea-8067-1a43b67ac975.png)

**Comment by edbusquets** [comment]
When handlebars.js version is above 4.6.0, the coverage report will be blank.

It works by downgrading the version to 4.5.3

add "handlebars": "4.5.3", to devDependencies

**Comment by xMort** [comment]
I will test that when I will have a bit of time and update the ticket. Thanks for the hint.

**Comment by coreyfarrell** [comment]
istanbul-reports 2.2.7 fixes this by removing handlebars.  You should force upgrade of that package instead of pinning handlebars.
