### ISSUE TITLE
Stray end tag div

### ISSUE THREAD

**Issue by grasbergerm** [istanbuljs/istanbuljs#584]
https://github.com/istanbuljs/istanbuljs/blob/1b52fe750d1f800c34dbff168614c0c73bd76026/packages/istanbul-reports/lib/html/index.js#L100

**Comment by grasbergerm** [comment]
https://github.com/istanbuljs/istanbuljs/pull/585

**Comment by bkardol** [comment]
I am experiencing issues with my build pipeline, throwing a lot errors on multiple html files in the coverage report.

`SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (213:9)
[error]   211 |                 at Fri Feb 05 2021 13:17:11 GMT+0000 (Coordinated Universal Time)
[error]   212 |             </div>
[error] > 213 |         </div>
[error]       |         ^^^^^^
[error]   214 |         <script src="../prettify.js"></script>
[error]   215 |         <script>
[error]   216 |             window.onload = function () {`

My guess is that it is related, I am certain this PR will resolve this for the html reporter. Is it possible this PR will get merged soon(ish)?

By the way: The same issue occurs on the html-spa report.

**Comment by grasbergerm** [comment]
I'm not sure who to tag to get more visibility by someone who can approve/merge, but I agree.

**Comment by coreyfarrell** [comment]
It will take some time to look at this, it's honestly not a high priority.  To review I will need to match up opening and closing divs, make sure we're removing the right one.

Side note you should never be processing the output of our HTML reports with any build tools.  If a browser fails to render properly this would be a priority, but errors from your build pipeline are not a priority as this is not a supported use case.

**Comment by bkardol** [comment]
You're right, I made changes earlier to the prettier config so it will skip the coverage directory. It's not causing any trouble visually so I understand that it's not a high prio.
