### ISSUE TITLE
Per-test coverage? 

### ISSUE THREAD

**Issue by ffMathy** [istanbuljs/istanbuljs#588]
Hi there!

I'm looking to get coverage per test, so that I can see which test ran through which lines. 

The use case for this is that I'm building a tool which can incrementally decide what tests to run, based on affected files from your GIT pending changes. 

Jest already does this, but I'm curious if they are doing it via Istanbul, or if they made their own code for it.

**Comment by coreyfarrell** [comment]
nyc has no concept of what a test is, so this is functionality which can only be provided by the test framework.  I was not aware jest supported this.  tap supports filtering coverage per test file, see document about [coverage maps](https://node-tap.org/docs/coverage/coverage-map/).

Closing this issue as it is out of scope for istanbuljs / nyc to provide more direct support.
