### ISSUE TITLE
HTML report with nested tree

### ISSUE THREAD

**Issue by VincentClair** [istanbuljs/istanbuljs#589]
Is there an option to render tree with nested folder like this old one https://github.com/gotwarlost/istanbul/pull/716 ?

**Comment by coreyfarrell** [comment]
You should check out the `htmlspa` report, this has UI to switch modes.

**Comment by VincentClair** [comment]
Thank you: works as expected :) 

For information, the `html-spa` (with a dash) is not listed here: https://istanbul.js.org/docs/advanced/alternative-reporters/
