### ISSUE TITLE
Class variable instrumentation breaks name inferences

### ISSUE THREAD

**Issue by novemberborn** [istanbuljs/istanbuljs#59]
This function starts to return `false` after instrumentation:

```js
function test () {
  var foo = class {};
  var bar = class baz {};
  var qux = class { static name() {} };
  return foo.name === "foo" &&
         bar.name === "baz" &&
         typeof qux.name === "function";
}
```

This is the test for *variables (class)* in the [`node-compat-table` for function names](http://node.green/#ES2015-built-in-extensions-function--name--property). [See source](https://github.com/kangax/compat-table/blob/c0a3b882b27e4e9f4ef449a1c985ee7857326b94/data-es6.js#L13009:L13016).

The instrumentation yields:

```js
  var foo = (++cov_2mofekog2n.s[0], class {});
  var bar = (++cov_2mofekog2n.s[1], class baz {});
  var qux = (++cov_2mofekog2n.s[2], class {
    static name() {
      ++cov_2mofekog2n.f[1];
    }
  });
```

Do the `class` expressions need to be instrumented? For comparison, with `var foo = function() {};` the output is:

```js
  var foo = function () {
    ++cov_2mofekog2n.f[1];
  };
```

See also https://github.com/novemberborn/function-name-support which contains a regression test for `istanbul-lib-instruments` behavior.

**Comment by bcoe** [comment]
@novemberborn we could do something like we do for exports where we hoist the line counter to outside the expression -- looks like the same edge-case.

**Comment by bcoe** [comment]
@novemberborn see:

https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/visitor.js#L147

maybe this could be generalized slightly.

**Comment by novemberborn** [comment]
@bcoe thanks for the pointers. PR in #60. It works with my `function-name-support` module.
