### ISSUE TITLE
`istanbul ignore else` does not work well with fast `if` return

### ISSUE THREAD

**Issue by JounQin** [istanbuljs/istanbuljs#605]
```js
/* istanbul ignore else */
if (condition) {
  return a
}

throw err // should not report
```

The following works, but it doesn't follow [`no-else-return`](https://eslint.org/docs/rules/no-else-return).

```js
/* istanbul ignore else */
if (condition) {
  return a
} else {
  throw err
}
```

**Comment by coreyfarrell** [comment]
You can do:

```js
/* istanbul ignore if */
if (!condition) {
  throw err
}

return a
```

Alternatively you can add `istanbul ignore next` before the throw statement in your original code.  It is out of scope for nyc to determine that `throw err` in your first example is an "else".
