### ISSUE TITLE
ERROR: No coverage files found, The coverage folder is not recognize for sonarQube 

### ISSUE THREAD

**Issue by vega178** [istanbuljs/istanbuljs#606]
Hi There!!, I was trying to upload the coverage report to the Sonar Qube server but it does not recognize and always is show me a 0,0 % of coverage even to show me the test cases scripts, when I execute the grunt-mocha-Istanbul task it generated the coverage root folder with the " lcov.info "file but it shows me an "ERROR: No coverage files found." message. 

![image](https://user-images.githubusercontent.com/15344903/116917978-f4201a00-ac14-11eb-8b8b-b886bc41a63f.png)
![image](https://user-images.githubusercontent.com/15344903/116919494-f71c0a00-ac16-11eb-8b7f-b9a752f866e5.png)

library version:  

1.  "istanbul": "^1.0.0-alpha.2"
2.  "grunt-mocha-istanbul": "^5.0.2",

Node version:  v14.16.0

**Comment by coreyfarrell** [comment]
The `istanbul` module is not maintained or supported.  That module was from https://github.com/gotwarlost/istanbul/.  The repo you posted this bug to is for `istanbuljs` modules which are used by `nyc`.
