### ISSUE TITLE
Windows: undefined path resolution for directory junctions

### ISSUE THREAD

**Issue by ChantOfAnAnt** [istanbuljs/istanbuljs#61]
Yeah, I opened this at archived repo istanbuljs-archived-repos/test-exclude#28. Sorry for the mess.

**Description**:

This case is from istanbuljs/nyc#554. Reopened here as suggested by @bcoe. Anything mentioned there applies. All files listings and version info located at [Gist](https://gist.github.com/ChantOfAnAnt/a042725eb52082df58731405d8a95df4). More specifics follows:

**Problem**:

Directory junctions on windows systems do not excluded from paths correctly.

**Case**:

First, a structure example. Here, `dir` is simple directory, while `junc` is junction to `dir` (made with `mklink /j junc dir`)

```
`-- expr
  +-- dir
  | `-- foo.js
  +-- junc >> dir
  +-- main.js
  `-- package.json
```

`main.js` is simple test:

```javascript
const assert = require('assert')

const exclude = require('test-exclude')

const junctionOnly = exclude({
  exclude: ['dir/']
})

assert.strictEqual(false, junctionOnly.shouldInstrument('dir/foo.js')) // GOOD
assert.strictEqual(true, junctionOnly.shouldInstrument('junc/foo.js')) // GOOD

const plainDirOnly = exclude({
  exclude: ['foo/']
})

assert.strictEqual(true, plainDirOnly.shouldInstrument('dir/foo.js')) // GOOD
assert.strictEqual(false, plainDirOnly.shouldInstrument('junc/foo.js')) // BAD
```

You can see that assert fails at excluding junctioned path.

**Comment by bcoe** [comment]
@ChantOfAnAnt thank you for opening this issue; I believe we have similar issues with the handling of symlinks on Linux/Unix systems -- not sure of the best solution, but it would be nice to figure out an approach.

**Comment by ChantOfAnAnt** [comment]
**OMG**, I need to sleep a little more. Wanted to dig up on case, but I put wrong dir there. Not `foo/` but `junc/`. And `junc/` runs all-good. As I understood, test-exclude doesn't do anything in particular to paths. Most of stuff is just pattern-matching. So, close issue?

**Comment by bcoe** [comment]
@ChantOfAnAnt great 👍 let me know if you bump into any more issues on Windows.
