### ISSUE TITLE
Hardcoded Babel config prevents code coverage for ESM TypeScript modules

### ISSUE THREAD

**Issue by yinzara** [istanbuljs/istanbuljs#614]
If I create an "src/index.ts" file with the following contents:
```
import { dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

export function someFunction() {
   console.log(__dirname)
}
```

and run `jest --coverage`, I get:
```
STACK: SyntaxError: unknown: import.meta may appear only with 'sourceType: "module"' (3828:53)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.
```

Unfortunately I can't rename my file to "mjs" as it would not be a TypeScript file and would fail compilation.

This seems to be caused by the `packages/istanbul-lib-instrument/src/read-coverage.js` lines:
```
function getAst(code) {
    if (typeof code === 'object' && typeof code.type === 'string') {
        // Assume code is already a babel ast.
        return code;
    }

    if (typeof code !== 'string') {
        throw new Error('Code must be a string');
    }

    // Parse as leniently as possible
    return parseSync(code, {
        babelrc: false,
        configFile: false,
        parserOpts: {
            allowImportExportEverywhere: true,
            allowReturnOutsideFunction: true,
            allowSuperOutsideMethod: true,
            sourceType: 'script',
            plugins: defaults.instrumenter.parserPlugins
        }
    });
}
```

Because the "sourceType" is hard coded as 'script', there is no way to change it to use 'module' and no way to modify the babel config otherwise.

**Comment by yinzara** [comment]
Just to note my jest.config.cjs is:
```
module.exports = {
  transform: { '\\.tsx?$': 'ts-jest' },
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  collectCoverageFrom: ['**/*.{js,jsx}'],
  coveragePathIgnorePatterns: [
    '/dist/',
    '/node_modules/',
    '.*\\.d\\.ts',
  ],
  moduleFileExtensions: ['js', 'json', 'jsx', 'node', 'ts', 'tsx'],
  testEnvironment: 'node',
  testMatch: ['**/?(*.)+(spec|test).(j|t)s?(x)'],
  globals: {
    'ts-jest': {
      useESM: true
    }
  }
}
```

If I do not set the 'ts-jest' config to `useESM: true`, I get  a slightly different error:
```
STACK: 
Failed to collect coverage from /myprojectpath/src/index.ts
ERROR: src/index.ts:25:46 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'.
```

**Comment by gitawego** [comment]
any update on this issue ? it prevents us from collecting coverage with jest

**Comment by piranna** [comment]
It seems I'm facing exactly the same issue, any clue?

**Comment by marceloavf** [comment]
Trying to migrate to ESM due to many packages from @sindresorhus requires it now, but really hard to get through these problems

Also: https://github.com/sindresorhus/p-queue/issues/152

**Comment by bcoe** [comment]
@marceloavf @piranna for what it's worth, I've been using [c8](https://github.com/bcoe/c8) these days for my projects that are ESM.

It's not perfect, but I find it works well enough for me.

**Comment by freshollie** [comment]
FYI for those using jest. Using the `v8` coverage provider is not only faster, but fixes this problem: 

https://jestjs.io/docs/configuration#coverageprovider-string

**Comment by jasonk** [comment]
For anybody else struggling with this, here is a gist with some patches you can apply using `patch-package` to kludge your way around the issue...
https://gist.github.com/jasonk/8616825033ba94cc77840c8c872497d9

**Comment by fohletex** [comment]
Unfortunately this patch didn't work for me (probably because I do not use babel in my project and just ts-node, resp. having anorther software version). I just fixed it be directly replacing the `script`-sourceType with `module`. Here's my patch for that to run in `patch-package`: https://github.com/fohletex/esm-patch-istanbul-lib-instrument

**Comment by SimenB** [comment]
https://github.com/istanbuljs/istanbuljs/releases/tag/istanbul-lib-instrument-v6.0.1
