### ISSUE TITLE
Help trying to make my own coverage reporter

### ISSUE THREAD

**Issue by joeycozza** [istanbuljs/istanbuljs#62]
I'm trying to make my own istanbul coverage reporter, but I can't find any kind of documentation that explains how I'd make my own and actually have nyc recognize it as a valid reporter. 

I've looked through the source code, and I can see that if I manually add my own code to node_modules/nyc/node_modules/istanbul-reports/lib/myCustomReporter/index.js that I can then use it in 
```nyc --reporter=myCustomReporter mocha```

Is there some documentation you could point me to in order to help me out with this?

Thanks for any help you can give me here.

**Comment by bcoe** [comment]
@joeycozza 👋 sorry for the slow response.

Perhaps you can join the [discussion here](https://github.com/istanbuljs/istanbuljs/issues/71) about writing some docs for Istanbul's API?
