### ISSUE TITLE
Switch case no longer ignorable via istanbul ignore next

### ISSUE THREAD

**Issue by isaacs** [istanbuljs/istanbuljs#64]
Here's a case: https://gist.github.com/isaacs/0d013bb96063f379242fba37f45ece63

Should be 100% test coverage.  Using nyc 10.2.0 it was.  But in nyc 11, it no longer is.

**Comment by bcoe** [comment]
narrowed regression down to this change:

"resolved": "https://registry.npmjs.org/babylon/-/babylon-6.16.1.tgz"
"resolved": "https://registry.npmjs.org/babylon/-/babylon-6.17.2.tgz"

**Comment by bcoe** [comment]
@isaacs please try `nyc@next` it should have a fix for this.

**Comment by isaacs** [comment]
Confirmed!
