### ISSUE TITLE
"E" is not showing in the HTML reporter for "implicit else" branches after https://github.com/istanbuljs/istanbuljs/pull/633

### ISSUE THREAD

**Issue by gareth-smyth** [istanbuljs/istanbuljs#649]
**Expected Behavior: how should things be working?**
When an "implicit else" statement is not covered the HTML reporter should show an "E" to the left of the "if" statement.

![expected](https://user-images.githubusercontent.com/6697040/140655164-7c71f07d-1e1b-4fdf-9618-b2838ad0327a.png)

**Observed Behavior: what did you observe happening instead?**
The heading correctly shows that a branch is not covered but the branch is not highlighted in the code view.

![actual](https://user-images.githubusercontent.com/6697040/140655169-fe5701a8-9c51-4e61-8f48-52a2564c91db.png)

**Code: provide a repository, or snippet of code, that reproduces the bug.**
```
if(1 === 1) {
    console.log(1);
}
```

** Configuration **
Node v14.17.2
NPM 6.14.13
Running Jest 27.3.1

** Quick analysis **
If I revert the change from this PR https://github.com/istanbuljs/istanbuljs/pull/633 it seems to work correctly.

Thanks,
Gareth

**Comment by bcoe** [comment]
@gareth-smyth thank you for the bug report  :+1: 

@adrian-burlacu-software any thoughts on this one?

**Comment by Powerplex** [comment]
I can confirm we have the same issue. The generated json is correct, showing "0" lines covered for missing `else` branches. The static website generated to show the coverage is showing a coverage lower than 100% BUT does not show where it is. 

The [E] (Else branch not covered) is not showing for implicit else only. If we add a simple `else { /* with nothing inside */ }` then we can see the coverage is missing. 

@gareth-smyth this is the exact same issue.

**Comment by adrian-burlacu-software** [comment]
@bcoe 
Sorry, this just hit my radar. I'll take a look to fix, hopefully by the end of the holiday break. Was lucky that I was Looking to make further improvements to this lib so I already made the time :)

Kind regards,
Adrian

**Comment by adrian-burlacu-software** [comment]
@bcoe 
Still waiting to validate, my gut feeling is that it's a downstream issue. We fixed the reporting data but not the HTML reporter.

**Comment by bcoe** [comment]
@adrian-burlacu-software :+1: thank you for starting to dig into this. I felt the recent additions to the library have added more value than this bug detracts, but would be nice to fix :smile:

**Comment by adrian-burlacu-software** [comment]
@bcoe 
Happy New Year to all! Fixed and fingers crossed extra tight in https://github.com/istanbuljs/istanbuljs/pull/663

**Comment by adrian-burlacu-software** [comment]
@gareth-smyth 
@Powerplex 
@bcoe 

Ok, fix was released in istanbul-reports 3.1.4. This issue is good to close :)

**Comment by bcoe** [comment]
@adrian-burlacu-software thanks for fixing this 👍
