### ISSUE TITLE
Track Flow with Istanbul

### ISSUE THREAD

**Issue by asicfr** [istanbuljs/istanbuljs#68]
Is it possible to use Istanbul to track the flow of an application at runtime (not for test) ?
The idea is instrumenting the code to trace the functions used during execution.
Thx

**Comment by J-Sek** [comment]
You might be interested in [e2e-istanbul](https://github.com/mahuntington/e2e-istanbul) and [this](https://github.com/gotwarlost/istanbul/issues/132) short thread from legacy repo.

I personally would recommend [Coverage tracking](https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage) offered by Google Chrome DevTools. It may not be the best choice if you wish to generate report or integrate with automatic functional tests, but it seems to be enough to gain some basic insight into what parts of your code are actually executed during certain scenarios.

**Comment by asicfr** [comment]
Thx
