### ISSUE TITLE
security issue with semver in istanbul-lib-instrument

### ISSUE THREAD

**Issue by zacmoss-jaspar** [istanbuljs/istanbuljs#727]
### Vulnerabilities found with npm audit.

```
istanbul-lib-instrument  >=1.2.0
Depends on vulnerable versions of @babel/core
Depends on vulnerable versions of semver
node_modules/istanbul-lib-instrument    
```

```
semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
```

Found in `istanbul-lib-instrument`:

```
  "dependencies": {
    "@babel/core": "^7.12.3",
    "@babel/parser": "^7.14.7",
    "@istanbuljs/schema": "^0.1.2",
    "istanbul-lib-coverage": "^3.2.0",
    "semver": "^6.3.0"
  },
```

babel devs are aware of semver issues and will be working on a fix - https://github.com/angular/angular-cli/issues/25431

However semver is still called directly in this package and can be updated 

### Expected outcome

No vulnerabilities found

### Suggestion

Update semver

**Comment by bcoe** [comment]
See: https://github.com/istanbuljs/istanbuljs/pull/732
