### ISSUE TITLE
Cannot read property 'fileCoverage' of undefined

### ISSUE THREAD

**Issue by battlesnake** [istanbuljs/istanbuljs#73]
When running:

```istanbul cover _mocha -- --bail --require babel-polyfill --compilers js:babel-register```

Using babel preset `latest` and plugin `istanbul`, I get the following errors (just messages, no stack traces), and they are swallowed somewhere, resulting in the tests subsequently running but no coverage report being generated.

```
Transformation error for /home/mark/ef/oc/qb/marshall/src/main.js ; return original code
Cannot read property 'fileCoverage' of undefined
Transformation error for /home/mark/ef/oc/qb/marshall/src/endpoint/db.js ; return original code
Cannot read property 'fileCoverage' of undefined
Transformation error for /home/mark/ef/oc/qb/marshall/src/config/index.js ; return original code
Cannot read property 'fileCoverage' of undefined
Transformation error for /home/mark/ef/oc/qb/marshall/src/config/db.js ; return original code
Cannot read property 'fileCoverage' of undefined
... et cetera ...
```

I've narrowed it down to `istanbul-lib-instrument/dist/instrumenter.js`, function `instrumentSync`, line `147` (dist), line `100` (source):

```this.fileCoverage = output.fileCoverage;```

I'm using `babel-plugin-istanbul` version:

```
      "version": "4.1.4",
      "integrity": "sha1-GN3oS/POMp/d8/QQP66SFFbY5Yc=",
```

And `istanbul-lib-instrument` version:

```
      "version": "1.7.3",
      "integrity": "sha1-klsjkWPqvdaMxASPUsL6T4mez6c=",
```

I see that `output` is initialised to `{}`, then reassigned in the AST visitor `exit` callback `output = ee.exit(path)`.  So `ee.exit` is returning undefined at some point,

**Comment by Akkuma** [comment]
I'm running into a similar issue when running through Jest. Basically, it works fine for the file that actually has a test associated with it, but when the file gets hit again it fails.

```
Failed to collect coverage from /Users/omni/Documents/git/browser-extension/browsers/chrome/lib/options/index.js
    ERROR: TypeError: Cannot read property 'fileCoverage' of undefined
    STACK: TypeError: Cannot read property 'fileCoverage' of undefined
    at Instrumenter.instrumentSync (/Users/omni/Documents/git/browser-extension/node_modules/istanbul-lib-instrument/dist/instrumenter.js:147:39)
    at module.exports (/Users/omni/Documents/git/browser-extension/node_modules/jest/node_modules/jest-cli/build/generateEmptyCoverage.js:39:18)
    at module.exports.error (/Users/omni/Documents/git/browser-extension/node_modules/jest/node_modules/jest-cli/build/reporters/CoverageWorker.js:51:20)
```

This same file has a test written against it and its coverage is then reported:
```
---------------------------------------|----------|----------|----------|----------|----------------|
File                                   |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------------------------|----------|----------|----------|----------|----------------|
All files                              |    33.94 |        0 |    13.64 |    33.94 |                |
 browsers/chrome/lib/options           |    31.43 |        0 |        5 |    31.43 |                |
  options-page.js                      |    31.43 |        0 |        5 |    31.43 |... 192,196,200 |
 tests/src/browsers/chrome/lib/options |      100 |      100 |      100 |      100 |                |
  options-page.spec.js                 |      100 |      100 |      100 |      100 |                |
---------------------------------------|----------|----------|----------|----------|----------------|
```

**Comment by athomann** [comment]
@Akkuma were you able to get this running with jest?

**Comment by athomann** [comment]
I'm able to resolve this error by using version `1.7.0` of `istanbul-lib-instrument`

**Comment by bcoe** [comment]
@battlesnake @athomann @Akkuma if you could please provide a branch of any of the repos having this issue, I'd be happy to help debug.

**Comment by athomann** [comment]
@bcoe https://github.com/athomann/istanbul-bug-repo 
Can reproduce by running `yarn install`  then `jest`

**Comment by bcoe** [comment]
@athomann thank you for the reproduction. I'm triaging a bunch of other tickets right now, but this will be near the top of the list of the next bug fixes I work on (unless you get bored and decide to start poking through the `istanbuljs` repo).

**Comment by bcoe** [comment]
@athomann something immediately jumps out at me. Jest itself already uses `babel-plugin-istanbul` to facilitate test coverage. Rather than configuring `babel-plugin-istanbul` in your `.babelrc`, you should just be using jest's coverage feature, I imagine the double instrumentation might be the root of the error.

**Comment by athomann** [comment]
That makes sense! Testing without and the error is gone.  Currently uploading to codecov to see if coverage is correct.

**Comment by athomann** [comment]
Coverage looks accurate.  Thanks for the help!

**Comment by athomann** [comment]
Created a PR for jest docs. https://github.com/istanbuljs/istanbuljs.github.io/pull/64

**Comment by bcoe** [comment]
@athomann awesome, looking at docs update now \o/

**Comment by derwaldgeist** [comment]
@bcoe Thanks a lot for the hint about the double instrumentation. I am migrating from nyc/mocha to jest and just forgot about the existing babel plugin :-)

**Comment by HugoGiraudel** [comment]
Hey there!

The double instrumentation definitely is the root of the problem. However, if the project needs `babel-plugin-instanbul` for other reasons (e.g. code coverage for Cypress), then the coverage feature from Jest no longer works properly.

Is there a way to work around this problem?

**Comment by zzsanduo** [comment]
> @athomann something immediately jumps out at me. Jest itself already uses `babel-plugin-istanbul` to facilitate test coverage. Rather than configuring `babel-plugin-istanbul` in your `.babelrc`, you should just be using jest's coverage feature, I imagine the double instrumentation might be the root of the error.

Thanks. It works for me. Once i remove the 'istanbul' plugin config in .babelrc,  there is no "Cannot read property 'fileCoverage' of undefined" error any more .

**Comment by bcoe** [comment]
@zzsanduo 👋 I'm glad it's working for you.

@HugoGiraudel perhaps take a look at https://github.com/bcoe/c8 as an alternative to `jest --coverage` eventually; It's my hope that we can eventually use v8's built in coverage.

**Comment by jdalton** [comment]
Is possible istanbul could detect a file is already instrumented and simply not instrument it again?

**Comment by coreyfarrell** [comment]
@jdalton it's designed to do so already but looking at the code I think this would fail if the filename changes between instrumentation requests.  So if you instrument src/index.js and output to dist/index.js, then try to instrument dist/index.js I think it won't recognize the file as already instrumented.

One thought I'm having is that maybe we could have the instrumenter insert `/* istanbul ignore file: already instrumented */`, in theory this would prevent instrumenting again no matter how you rename, but if further build steps strip comments this would fail too.  I can't think of a completely fail-safe detection method.

**Comment by jdalton** [comment]
I'm having to add my own detection so if nyc could pick that up in some way, that would rock.

**Comment by Akkuma** [comment]
> One thought I'm having is that maybe we could have the instrumenter insert `/* istanbul ignore file: already instrumented */`, in theory this would prevent instrumenting again no matter how you rename, but if further build steps strip comments this would fail too. I can't think of a completely fail-safe detection method.

I feel like using a combination of the two would lead to less cases of error out of the box even if it isn't foolproof.

**Comment by storenth** [comment]
Just use different **_environments_** in .babelrc to avoid `babel-plugin-istanbul` double effect. 
```
"env": {
		"production": {
			"plugins": [
				"transform-react-remove-prop-types"
			]
		},
		"dev": {
			"plugins": [
				"transform-decorators-legacy",
                                 [
                                 "istanbul",{
						"include": [
							"**/api/*.js"
						],
						"exclude": [
							"**/__test__/*.js"
						]
				}]
                        ]}
}
```
