### ISSUE TITLE
Simple fix: Filter not working on firefox

### ISSUE THREAD

**Issue by MManke188** [istanbuljs/istanbuljs#730]
The filter added in this commit isn't working for me on firefox:
eab47f7

The way I got it to work is to convert "oninput" to camelCase ("onInput") but of course every time I regenerate the coverage report (I'm using "jest --coverage") it converts it back to all lowercase.
The console error I'm getting on firefox is:
"onInput is not defined"

Not sure if there's something on my end I could fix too, or if there's some reason why converting oninput to camelCase is not a good idea but would be nice if it could be fixed otherwise

(specifically this is what causes the problem:
packages/istanbul-reports/lib/html/assets/sorter.js
```javascript
// loads the search box
function addSearchBox() {
    var template = document.getElementById('filterTemplate');
    var templateClone = template.content.cloneNode(true);
    templateClone.getElementById('fileSearch').oninput = onFilterInput; // This is the line that causes the problem
    template.parentElement.appendChild(templateClone);
}
```

**Comment by bcoe** [comment]
Hello @MManke188 the documented event handler in the HTML standard is [`oninput`](https://html.spec.whatwg.org/multipage/webappapis.html#handler-oninput). It is odd to me that `onInput` would be working for you but not `oninput`.

What behavior does the filter have in Firefox without your modification? any errors in the console?

**Comment by MManke188** [comment]
Yes indeed it seems odd to me too
Without the modification I can type in the field but it simply doesn't filter.

The specific error I'm getting every time I type a character is:

Uncaught ReferenceError: onInput is not defined
    oninput file:///Users/me/myApp/coverage/lcov-report/index.html:1
    
    
With the "fix" it works as expected and I get no errors in the console.
(on Safari for everything works either way by the way)

**Comment by smigles** [comment]
@bcoe, I have the same problem in Firefox 118.

**Comment by bcoe** [comment]
@MManke188 something jumps out at me, which is that the ReferenceError is for `onInput`. What happens if you change this line:

https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/lib/html/index.js#L89

To `oninput` rather than `onInput`?

**Comment by MManke188** [comment]
I changed that line and the same error still persists, however I think I am missing a step, since I also updated the text above however those text changes are also not reflected when viewing the coverage report
```
Changed Filter:  // used to be just "Filter"
 <input oninput="oninput()" type="search" id="fileSearch">
```

Already tried to run jest --coverage, reinstall the packages, run the coverage command again

**Comment by alexristich** [comment]
Ran into this issue today and decided to dig a bit. Here's a small change that should fix it: https://github.com/istanbuljs/istanbuljs/pull/758

**Comment by bcoe** [comment]
@MManke188 I've landed @alexristich's patch in the upcoming release, please let me know if this does the trick for you.
