### ISSUE TITLE
sourceRoot is ignored

### ISSUE THREAD

**Issue by ishitatsuyuki** [istanbuljs/istanbuljs#76]
The code doesn't honor `sourceRoot` property at all, which Chrome correctly treats it by concatenating `sourceRoot` with `sources`. Such maps are mainly generated by [`gulp-sourcemaps`](https://www.npmjs.com/package/gulp-sourcemaps).

The [test](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/test/specs/input-source-map.yaml) should be altered to have a version with `sourceRoot`.

**Comment by ishitatsuyuki** [comment]
I can no longer reproduce this issue, and I probably messed something up with Gulp. The `sourceRoot` was working properly as the correct implementation `source-map` is used.

**Comment by bcoe** [comment]
@ishitatsuyuki awesome 👍 let me know if you bump into any more issues.
