### ISSUE TITLE
treshold => threshold typo

### ISSUE THREAD

**Issue by niftylettuce** [istanbuljs/istanbuljs#83]
can't seem to find exactly what package this is caused from, but here's the output:

```log
Start time: (2017-09-09 16:48:46 UTC) [treshold=1%]  <===== TYPO HERE
#  module  time  %
Total require(): 788
Total time: 43.6s
```

**Comment by davisjam** [comment]
FWIW "treshold" appears nowhere in the istanbuljs source.

'''
(20:40:01) Jamies-MBP:/tmp/istanbuljs $ grep -R treshold . | wc -l
       0
'''

**Comment by katerberg** [comment]
@niftylettuce What command are you running to cause this to occur?

**Comment by niftylettuce** [comment]
It's due to <https://github.com/Jaguard/time-require/pull/9> and <https://github.com/avajs/ava/blob/master/package.json#L143>.  I've already fixed this and published my own fork of `time-require` as `@ladjs/time-require` at <https://github.com/ladjs/time-require> and submitted a pull request to ava to patch it at <https://github.com/avajs/ava/pull/1621>.

I'm using ava along with nyc for code coverage and so that's why I thought it was this issue at first.  Thankfully [ripgrep](https://github.com/BurntSushi/ripgrep) made it easy to figure out what the problem was `rg "treshold" node_modules` did the trick.
