### ISSUE TITLE
no coverage report if source file is loaded by vm.runInContext

### ISSUE THREAD

**Issue by pangrr** [istanbuljs/istanbuljs#85]
I think we need to add hook to vm.runInContext in a similar way that we hook vm.runInThisContext. Maybe for vm.runInNewContext as well.
Because some projects need to use vm.runInContext to create a testing context for code that is supposed to run in that context.

**Comment by pangrr** [comment]
I am trying to make a PR to add hook to vm.runInContext but cannot find the global coverage variable to hook the vm context to. I guess the global coverage variable could be '__coverage__' but it is not initialized in when hook is called. Anyone give a hint?

**Comment by pangrr** [comment]
It turns out ```` __coverage__ ```` is in the vm context. Thus it needs to be exported to global.

**Comment by coreyfarrell** [comment]
It appears this was fixed by the linked PR's so I'm going to close this issue.  If further work is needed to resolve this issue let us know and we can reopen.

**Comment by JoHuang** [comment]
I got the same issue when I use Jest. 
How to make hooks work in Jest?
Thanks
