### ISSUE TITLE
npm install error in root directory

### ISSUE THREAD

**Issue by pangrr** [istanbuljs/istanbuljs#86]
lerna ERR! execute Error: spawn yarn ENOENT
lerna ERR! execute     at notFoundError (C:\Users\rpang27\Desktop\GitHub\istanbuljs\node_modules\cross-spa
wn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Users\rpang27\Desktop\GitHub\istanbuljs\node_modules\cross-spaw
n\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Users\rpang27\Desktop\GitHub\istanbuljs\node_modules\cr
oss-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: spawn yarn ENOENT
lerna ERR! execute     at notFoundError (C:\Users\rpang27\Desktop\GitHub\istanbuljs\node_modules\cross-spa
wn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Users\rpang27\Desktop\GitHub\istanbuljs\node_modules\cross-spaw
n\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Users\rpang27\Desktop\GitHub\istanbuljs\node_modules\cr
oss-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute   stack: 'Error: spawn yarn ENOENT\n    at notFoundError (C:\\Users\\rpang27\\Desktop\\
GitHub\\istanbuljs\\node_modules\\cross-spawn\\lib\\enoent.js:11:11)\n    at verifyENOENT (C:\\Users\\rpan
g27\\Desktop\\GitHub\\istanbuljs\\node_modules\\cross-spawn\\lib\\enoent.js:46:16)\n    at ChildProcess.cp
.emit (C:\\Users\\rpang27\\Desktop\\GitHub\\istanbuljs\\node_modules\\cross-spawn\\lib\\enoent.js:33:19)\n
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)',
lerna ERR! execute   errno: 'ENOENT',
lerna ERR! execute   code: 'ENOENT',
lerna ERR! execute   syscall: 'spawn yarn',
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: '\'yarn\' is not recognized as an internal or external command,\r\noperable p
rogram or batch file.\r\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'yarn install --mutex network:42424 --non-interactive',
lerna ERR! execute   timedOut: false }

**Comment by coreyfarrell** [comment]
I suspect this was an issue with an early release of `yarn` (based on the date of this ticket you were using yarn@1.0.1 or older).

Let us know if you are still having an issue with current version of yarn.

**Comment by coreyfarrell** [comment]
Without further information I have to assume this was an issue in the package manager which has since been resolved.  If I'm incorrect please provide updated information.
