### ISSUE TITLE
Uncovered block navigation for html reporter

### ISSUE THREAD

**Issue by Gidgidonihah** [istanbuljs/istanbuljs#88]
Many html code coverage reports I've worked in the past have had some shortcut to navigate to the next/previous uncovered code block. (j/k, f/b, n/b, n/p, etc.)

I'd love to see that in Istanbul's reports.

So much in fact, that I'd open a PR right now if I weren't under deadline.

**Comment by bcoe** [comment]
@Gidgidonihah I would love help implementing this when you're less slammed with work, feel free to join our community slack: devtoolscommunity.herokuapp.com if you want to collaborate in person.
