### ISSUE TITLE
hookRunInThisContext doesn't use current runInThisContext API

### ISSUE THREAD

**Issue by jason0x43** [istanbuljs/istanbuljs#89]
#The `vm.runInThisContext` hook assumes the second argument to `runInThisContext` [is a string](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-hook/lib/hook.js#L139). However, the argument has been an options object for quite a while now (I believe since Node 0.10 or 0.12). This prevents Istanbul from instrumenting modules instantiated by calling `Module#_compile` (or by calling `runInThisContext` using the proper API).

**Comment by CodeTroopers** [comment]
@jason0x43 could you perform a test with the `next` version
istanbuljs/nyc#902
also this issue may be concerned theintern/intern#912
