### ISSUE TITLE
Running coverage on Linux (RHEL6). SyntaxError: Unexpected identifier 

### ISSUE THREAD

**Issue by Phocea** [istanbuljs/istanbuljs#91]
Hello,

Executing nyc for coverage on my project build under Linux 2.6.32-504.el6.x86_64 return the following stackTrace.
Same command work properly under windows. any ideas on how to fix it please ?

> [INFO] > nyc npm test
> [INFO] 
> [ERROR] /var/lib/jenkins/jobs/OpUi/jobs/OpUI-React/jobs/OpUI-React_Core_Maven_Build/workspace/opui-client/node/npm:2
> [ERROR] (set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
> [ERROR]         ^^^^^
> [ERROR] SyntaxError: Unexpected identifier
> [ERROR]     at exports.runInThisContext (vm.js:73:16)
> [ERROR]     at Object.vm.runInThisContext (/var/lib/jenkins/jobs/OpUi/jobs/OpUI-React/jobs/OpUI-React_Core_Maven_Build/workspace/opui-client/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:141:16)
> [ERROR]     at Module._compile (module.js:543:28)
> [ERROR]     at Module.replacementCompile (/var/lib/jenkins/jobs/OpUi/jobs/OpUI-React/jobs/OpUI-React_Core_Maven_Build/workspace/opui-client/node_modules/nyc/node_modules/append-transform/index.js:58:13)
> [ERROR]     at module.exports (/var/lib/jenkins/jobs/OpUi/jobs/OpUI-React/jobs/OpUI-React_Core_Maven_Build/workspace/opui-client/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
> [ERROR]     at Object.<anonymous> (/var/lib/jenkins/jobs/OpUi/jobs/OpUI-React/jobs/OpUI-React_Core_Maven_Build/workspace/opui-client/node_modules/nyc/node_modules/append-transform/index.js:62:4)
> [ERROR]     at Module.load (module.js:488:32)
> [ERROR]     at tryModuleLoad (module.js:447:12)
> [ERROR]     at Function.Module._load (module.js:439:3)
> [ERROR]     at Function.Module.runMain (module.js:605:10)
> [INFO] ----------|----------|----------|----------|----------|----------------|
> [INFO] File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
> [INFO] ----------|----------|----------|----------|----------|----------------|
> [INFO] All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
> [INFO] ----------|----------|----------|----------|----------|----------------|
> [ERROR] 
> [ERROR] npm ERR! Linux 2.6.32-504.el6.x86_64
> [ERROR] npm ERR! argv "/var/lib/jenkins/jobs/OpUi/jobs/OpUI-React/jobs/OpUI-React_Core_Maven_Build/workspace/opui-client/node/node" "/var/lib/jenkins/jobs/OpUi/jobs/OpUI-React/jobs/OpUI-React_Core_Maven_Build/workspace/opui-client/node/node_modules/npm/bin/npm-cli.js" "run" "coverage"
> [ERROR] npm ERR! node v7.5.0
> [ERROR] npm ERR! npm  v4.1.2
> [ERROR] npm ERR! code ELIFECYCLE
> [ERROR] npm ERR! opui-client@0.1.0 coverage: `nyc npm test`
> [ERROR] npm ERR! Exit status 1

My package.json looks like this:

```
{
  "name": "opui-client",
  "version": "0.1.0",
  "private": true,
  "homepage": "/OpUi",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-register": "^6.26.0",
    "babel-plugin-istanbul": "^4.1.4",
    "babel-preset-react-app ": "^3.0.2",
    "cross-env": "5.0.5",
    "expect.js": "^0.3.1",
    "istanbul": "^0.4.5",
    "istanbul-instrumenter-loader": "^3.0.0",
    "jsdom": "^11.2.0",
    "jsdom-global": "^3.0.2",
    "enzyme": "^2.9.1",
    "mocha": "^3.5.2",
    "nyc": "^11.2.1",
    "react-test-renderer": "^15.6.1"
  },
  "dependencies": {
    "admin-on-rest": "^1.3.1",
    "aor-embedded-array": "0.0.2",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "~5.0.4",
    "react-router-dom": "~4.1.0",
    "react-tap-event-plugin": "~2.0.1",
    "react-scripts": "1.0.13"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "cross-env NODE_ENV=test mocha --opts ./config/mocha.opts",
    "coverage": "nyc npm test",
    "eject": "react-scripts eject"
  },
   "nyc": {
    "include": [
      "src/**/*.*"
    ],
    "exclude": [
      "src/test/**/*.*",
      "src/modules/**/resources/simple/*.*"
    ],
    "extension": [
      ".js",
      ".jsx"
    ],
   "all": true,
   "sourceMap": false,
   "instrument": false,
   "reporter": [
      "lcov",
      "text"
    ],
    "report-dir": "target/coverage"
  },
  "babel": {
  	"env": {
    	"test": {
      		"plugins": [ "istanbul" ]
    	}
  	},
  	"presets": ["react-app"]
  }
}
```

**Comment by bcoe** [comment]
@Phocea I think this will most likely be an issue with [spawn-wrap](https://github.com/tapjs/spawn-wrap) I suggest also opening up an issue on this repo.

**Comment by coreyfarrell** [comment]
By default nyc 15.0.0 does not use spawn-wrap by default, it instead uses `node-preload` which avoids these special scripts.  The updated nyc requires node.js 8.9.0 but it will resolve this issue.
